### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by randomhammer** [pydoit/doit#104]
I am trying to learn doit by following the tutorial, and am unable to get anywhere at all. I copied the first example, code follows:

```python
def task_hello():
    """hello"""

    def python_hello(targets):
        with open(targets[0], "a") as output:
            output.write("Python says Hello World!!!\n")

    return {
        'actions': [python_hello],
        'targets': ["hello.txt"],
        }
```

When I try to run, I get the following:

```bash
Chris$ doit
Traceback (most recent call last):
  File "/Users/Chris/anaconda/envs/spacewx/bin/doit", line 7, in <module>
    from doit.command import main
  File "/Users/Chris/anaconda/envs/spacewx/lib/python3.4/site-packages/doit/command.py", line 116
    print textwrap.dedent(text)
```

It does not matter what I put in the `dodo.py` file, I get the same error. The lines appear to be from doit's source, not anything that I am doing.

I am running Anaconda Python 3.4 on OSX Yosemite. I have no idea why I keep getting this error, or how to fix, it. Is doit broken, or am I? I imagine it is something simple, but I appear (by googling) to be the only person in the known universe experiencing this problem.

**Comment by schettino72** [comment]
how did you install doit?

I guess you have installed something else called `doit`.

**Comment by randomhammer** [comment]
I installed it through the `conda` package manager, which appears to be the issue. I uninstalled it, reinstalled using `pip` and it worked. The issue is *not* invalid, the package according to `conda` was doit -0.29.0, the same as the one that `pip` installed. There must be something wrong with the version that `conda` installs.

Thanks!

**Comment by schettino72** [comment]
so you should complain to `conda` guys. it is their bug :grin: 

`doit` doesnt have any file called `command.py`
