### ISSUE TITLE
doit changes working directory.

### ISSUE THREAD

**Issue by FrankStain** [pydoit/doit#108]
So, here is a problem.
https://github.com/pydoit/doit/blob/master/doit/loader.py#L94

If i need call doit script (script works at current CWD) from other directory, doit will rewrite CWD and script itself will make not effect where it must.

Consider it as uncommon behaviour.
Here example.

test_doit.py
```python
#! /usr/bin/doit -f
# -*- coding: utf-8 -*-

import os
import sys

print( os.path.normpath( os.getcwd() ) )
```

input :
```
D:\dev\projects\foo>..\test_doit.py
```
output :
```
D:\dev\projects
```

But if first line of 'test_doit.py' will be changed to `#! /usr/bin/python3`, output will be:
```
D:\dev\projects\foo
```

**Comment by schettino72** [comment]
Changes in the working directory is the expected behavior.

Your use case also makes and it is already easily achieved. 
I guess the docs could show exactly how to achieve this using: `get_initial_workdir()` and `--dir` option.

http://pydoit.org/cmd_run.html#get-initial-workdir

**Comment by FrankStain** [comment]
@schettino72 Ok, i see it now. :)
As i can see, `get_initial_workdir()` already exists in 0.29 release.
Docs shows how it can be used. So i close this issue.

**Comment by schettino72** [comment]
many times questions shows that the docs can be improved :smile:
