### ISSUE TITLE
Equivalent paths are considered different (should use os.path.normpath)

### ISSUE THREAD

**Issue by DarwinAwardWinner** [pydoit/doit#109]
I have one task with a (auto-generated) target of "./some_file" and another task with a dependency of "some_file", and doit failed to recognize the dependency between the two tasks, presumably because is uses string equality to determine whether two paths are not equal. I recognize that, in the presence of symlinks, hard links, bind mounts, and other such things, the general problem of determining whether two paths lead to the same file is difficult, but I think at the very least doit should run `os.path.normpath` before comparing two paths for equality.

**Comment by schettino72** [comment]
There is also the issue about detecting if 2 paths are the same file on case-insensitive file systems.

This came up before and I decided it is a `wontfix`. You can easily use `normpath` yourself when required.

I am keeping this open as `doc` issue to make sure this behavior is documented somewhere.
