### ISSUE TITLE
drop python 2 compatibility

### ISSUE THREAD

**Issue by schettino72** [pydoit/doit#112]
time to move on...

**Comment by saimn** [comment]
Why ? Will you really benefit from the python 3 features and does it justify that you drop python 2 support ? BTW I use doit with a python2 only scientific code base, we have plans for python 3 compatibility but it is clearly not a priority (don't break it if it works ...).

**Comment by schettino72** [comment]
First **I** don't use python 2 anymore for almost two years. So for me supporting it is just a hassle. 

For those people still using python 2 you can always keep using the last version of doit that supports python 2. I guess that if you can live without newer python features you can also leave without newer doit features...

Short term I plan to work on #94 and adding colors to terminal. While both could be done for both python 2 and 3, it is definitely not fun.

Long term I plan to add some built-in support for executing tasks remotely and having some kind of UI where you can interact with a running instance. Both will rely heavily on asyncio.

**Comment by Kwpolska** [comment]
Would you mind waiting at least until [next year](https://getnikola.com/blog/env-survey-results-and-the-future-of-python-27.html)?

**Comment by schettino72** [comment]
No problem to hold next release... 

But why? Does it make any difference for you guys? Don't you have pinned doit version?

**Comment by Kwpolska** [comment]
It’s easier if we keep in sync.

And no, it isn’t due to complaints (and it’s hard to package for distros).

But if you do decide to do it this year, we’ll just make an emergency release.

**Comment by infamy** [comment]
With the whole idea of this being flexible, would removing python 2 support mean that you would be discouraging people from using it for automation on older projects? Seems sort of against the grain of the whole concept of automation.

**Comment by vlcinsky** [comment]
This is very disappointing. I was just considering 100 USD contribution via [INDIEGOGO](https://www.indiegogo.com/projects/doit-python-automation-tool-release-0-30#/) and when checking proposed new features, I have found, you are going to drop support for Python version we use in production.

There is couple of reasons to keep Python 2.x (at least 2.7) support
# Couple of resons to keep Python 2.x supported

## `doit` as `make` replacement for Python projects

I was wondering, why some Python based projects keep using `make` when there is `doit` solution in place.

Dropping support for Python 2.x means, most of such projects could not use as many still plan to support this version.

## AWS Lambda supports only Python 2.7

`doit` has excellent dependency detection and I was planning to use it as part of solution run on AWS Lambda. AWS does support only Python 2.7.

Also Google App Engine supports only Python 2.7.

# Conclusions

All the comments on this issue are either surprised by the change or disappointed. There is probably some reason for it.

Pinning `doit` version is only partial solution. Shall I recommend anybody with Python 2/3 project to rewrite `Makefile` to `doit`? Then I have to tell them "pin the version", as for Python 2.x it is not developed any more.

Some of the features you talk about (colours) are not worth dropping Python 2 compatibility (and can be done anyway.

Timing of this change is bad for the moment your donation campaign on INDIEGOGO. Most of the proposed changes seem to be still easy with Python 2. 

Proposal: What about starting `doit3` which would support only Python 3.x?

It is really sad to see such a good solution moving out of my reach.

**Comment by vlcinsky** [comment]
As **AWS Lambda supports python 3.6** now, my previous comments are less relevant.
