### ISSUE TITLE
config_changed() isn't ideal when the config is a nested dictionary (expecially under Py3)

### ISSUE THREAD

**Issue by lelit** [pydoit/doit#113]
When the config is a dictionary containing other dictionaries, `config_changed()` may produce different results even when the config didn't change: while it sorts the outer dictionary keys, inner dictionaries are simply stringified with `repr()`, and there's no guarantee that their items are visited in the same order. Under Python 3, by default, you have the guarantee that they are not, thanks to the randomization controlled by the envvar `PYTHONHASHSEED`.

I think that the easiest fix is replacing the whole logic with `pprint.pformat()`, that recursively sorts dictionary keys.
##

**Comment by lelit** [comment]
FYI, I referenced this in https://github.com/docker/compose/issues/2342

**Comment by schettino72** [comment]
fix by using json (with sort_keys=True)
