### ISSUE TITLE
Using equal signs in sub-task name makes it unselectable

### ISSUE THREAD

**Issue by tbekolay** [pydoit/doit#117]
I wanted to make some subtasks with names related to their parameters; the full name would be something like `task1:param=a`. When I did this, the subtask showed up fine when doing `doit list --all`, and ran with `doit task1`. But if I tried `doit task1:param=a` it would silently run nothing. Removing the equal sign in the subtask name solved the problem.

Ideally, it would be possible to use equal signs in the name, but if that's not possible, it would be nice to get a warning / error that the task I'm trying to run can't be found, or contains a character that doesn't work.

**Comment by schettino72** [comment]
That is because `=` is used to pass global variables through the command line.

So `doit` should give an error if `=` is present in the name. The docs should also mention that somewhere...
