### ISSUE TITLE
Dependencies on files created by `@create_after` tasks don't work

### ISSUE THREAD

**Issue by DarwinAwardWinner** [pydoit/doit#122]
With the following `dodo.py` (based on the example from http://pydoit.org/task_creation.html#delayed-task-creation ):

```python
#!/usr/bin/env doit -f --check_file_uptodate=timestamp -n 100

import glob
from doit import create_after

@create_after(executed='early', target_regex='.*\.mid')
def task_build_step1():
    for inf in glob.glob('*.in'):
        yield {
            'name': inf,
            'actions': ['cp %(dependencies)s %(targets)s'],
            'file_dep': [inf],
            'targets': [inf[:-3] + '.mid'],
            'clean': True,
        }

@create_after(executed='early', target_regex='.*\.out')
def task_build_step2():
    for inf in glob.glob('*.in'):
        yield {
            'name': inf[:-3] + '.mid',
            'actions': ['cp %(dependencies)s %(targets)s'],
            'file_dep': [inf[:-3] + '.mid'],
            'targets': [inf[:-3] + '.out'],
            'clean': True,
        }

def task_early():
    """a task that create some files..."""
    inter_files = ('a.in', 'b.in', 'c.in')
    return {
        'actions': ['touch %(targets)s'],
        'targets': inter_files,
        'clean': True,
    }
```

Running `doit build_step2` fails because it doesn't know to execute build_step1 first, despite the file dependency: 

```
$ doit build_step2
.  early
.  build_step2:a.mid
cp: cannot stat ‘a.mid’: No such file or directory
########################################
TaskFailed - taskid:build_step2:a.mid
Command failed: 'cp a.mid a.out' returned 1
```

**Comment by DarwinAwardWinner** [comment]
Note that this can be worked around by using a task dependency on build_step1 in build_step2, but that is suboptimal both because it is redundant with the file dependency and because it results in excessive dependencies, e.g. subtask `build_step2:a.mid` now depends spuriously on all three subtasks of step 1 :`build_step1:b.in1`, `build_step1:b.in1`, and `build_step1:c.in1`

**Comment by schettino72** [comment]
`target_regex` is used only on command line `run`. 
It doesnt try to guess by looking at `file_dep`, and even if it did the result would be similar to using `task_dep` right?

**Comment by DarwinAwardWinner** [comment]
So what is the solution here? Using `task_dep` works, but is not ideal, since you cannot declare dependencies on subtasks, so you just have to declare that every the subtask of `build_step2` depends on `build_step1`, which is not accurate: the `build_step2:a.mid` subtask should only depend on `build_step1:a.in` subtask, not the whole `build_step1` task. This can make a big difference in execution time for very long-running tasks. (I'm using doit to automate a lengthy computational pipeline.)

Wouldn't it be possible to resolve this automatically without a `task_dep` by matching a task's file dependencies against the `target_regex` properties of other delayed tasks, and then forcing creation of any matching tasks in order to check if one of them would actually provide the required file? I'd be willing to try and implement this when I have the time.

**Comment by schettino72** [comment]
I guess you have some misunderstanding of `task_dep`...

I think your problem can be solved in a simpler way... Would this solve your problem?

```
@create_after(executed='early', target_regex='.*\.out', creates=['build_step1', 'build_step2'])
def task_build():
    for inf in glob.glob('*.in'):
        yield {
            'basename': 'build_step1',
            'name': inf,
            'actions': ['cp %(dependencies)s %(targets)s'],
            'file_dep': [inf],
            'targets': [inf[:-3] + '.mid'],
            'clean': True,
        }

    for inf in glob.glob('*.in'):
        yield {
            'basename': 'build_step2',
            'name': inf[:-3] + '.mid',
            'actions': ['cp %(dependencies)s %(targets)s'],
            'file_dep': [inf[:-3] + '.mid'],
            'targets': [inf[:-3] + '.out'],
            'clean': True,
        }
```

**Comment by DarwinAwardWinner** [comment]
Your suggested solution using a single task builder function does indeed cause the dependencies to be resolved properly, although it also seems to break `doit clean` at the same time, which might be an acceptable trade-off.

I'm curious, though, as to what I'm misunderstanding about `task_dep`. If I could declare a `task_dep` of `build_step2:a.mid` on the subtask `build_step1:a.in` (and likewise for b and c), that would solve my problem as well (at the cost of only some minor duplication of information), but dependencies on subtasks result in a KeyError. Using my example dodo.py above and adding `'task_dep': ['build_step1:' + inf],` to `build_step2`, I get the following traceback:

```
$ doit build_step2:a.mid
.  early
Traceback (most recent call last):
  File "/usr/local/opt/pyenv/versions/2.7.11/lib/python2.7/site-packages/doit/doit_cmd.py", line 168, in run
    return command.parse_execute(args)
  File "/usr/local/opt/pyenv/versions/2.7.11/lib/python2.7/site-packages/doit/cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "/usr/local/opt/pyenv/versions/2.7.11/lib/python2.7/site-packages/doit/cmd_base.py", line 405, in execute
    return self._execute(**exec_params)
  File "/usr/local/opt/pyenv/versions/2.7.11/lib/python2.7/site-packages/doit/cmd_run.py", line 253, in _execute
    return runner.run_all(self.control.task_dispatcher())
  File "/usr/local/opt/pyenv/versions/2.7.11/lib/python2.7/site-packages/doit/runner.py", line 247, in run_all
    self.run_tasks(task_dispatcher)
  File "/usr/local/opt/pyenv/versions/2.7.11/lib/python2.7/site-packages/doit/runner.py", line 206, in run_tasks
    node = task_dispatcher.generator.send(node)
  File "/usr/local/opt/pyenv/versions/2.7.11/lib/python2.7/site-packages/doit/control.py", line 625, in _dispatcher_generator
    next_step = node.step()
  File "/usr/local/opt/pyenv/versions/2.7.11/lib/python2.7/site-packages/doit/control.py", line 333, in step
    return next(self.generator)
  File "/usr/local/opt/pyenv/versions/2.7.11/lib/python2.7/site-packages/doit/control.py", line 342, in _func
    for value in decorated(*args, **kwargs):
  File "/usr/local/opt/pyenv/versions/2.7.11/lib/python2.7/site-packages/doit/control.py", line 451, in _add_task
    yield self._gen_node(node, task_dep)
  File "/usr/local/opt/pyenv/versions/2.7.11/lib/python2.7/site-packages/doit/control.py", line 372, in _gen_node
    node = ExecNode(self.tasks[task_name], parent)
KeyError: 'build_step1:a.in'
```

So I guess it's not possible to declare dependencies on subtasks. Meanwhile, adding `'task_dep': ['build_step1'],` to `build_step2` works, but executes additional subtasks unnecessarily (and, in the context of long-running tasks, inhibits parallelism between steps 1 and 2).

```
$ doit build_step2:a.mid
.  early
.  build_step1:a.in
.  build_step1:b.in
.  build_step1:c.in
.  build_step2:a.mid
```

Still, this seems to be my best option if I need `doit clean` to work.
