### ISSUE TITLE
clean dependencies in reverse order

### ISSUE THREAD

**Issue by aquavitae** [pydoit/doit#124]
It would make sense to me for `doit clean` to clean tasks in the reverse order that they run, but it looks from the code like there is a deliberate reason that it does not.  In my case, the first command generates a bunch of files which drive the second command, including it's cleanup phase.  So if I do `doit -c clean` the second cleanup fails.  It would be interesting to know the reasoning behind not running them in reverse order.  If there isn't a clear reason, could it be reversed?  Or at least provide some options in the task definition for reversing the clean order (or defining clean dependencies)

**Comment by schettino72** [comment]
>  but it looks from the code like there is a deliberate reason that it does not

from where you get that?
