### ISSUE TITLE
tasks for calculated file dependencies are not executed

### ISSUE THREAD

**Issue by ebak** [pydoit/doit#127]
The attached doit script tries to build 2 binaries: 'release.bin', 'debug.bin'. These binaries are composed from generated source files, the name of these generated files are not known at task creation time.
The tasks for 'release.bin' and 'debug.bin' use calculated dependencies: 'generatedDep:release', 'generatedDep:debug'. These dependency tasks executes the 'generator' task, as setup task, which produces .cpp sources. After the execution of the 'generator' task 'task_generatedObjs()' executed, as a delayed task, which creates tasks for producing .o files from the generated .cpp files.
The 'release.bin' and  'debug.bin' tasks get the right file dependencies (.o files) from the dependency calculator. But those files don't exist, because those tasks, which would produce .o files from the generated .cpp files, are not executed.

See: 
[build.py.txt](https://github.com/pydoit/doit/files/159879/build.py.txt)
[https://groups.google.com/forum/#!topic/python-doit/6TEbOM8SU7k](url)

Here is the scripts output:

$ ./build.py 
-- obj/debug/Main.o
-- obj/release/Main.o
.  generator
generator running
.  generatedDep:debug
getDep(debug)
fileDep=['obj/debug/res0.o', 'obj/debug/res1.o', 'obj/debug/res2.o']
.  generatedDep:release
getDep(release)
fileDep=['obj/release/res0.o', 'obj/release/res1.o', 'obj/release/res2.o']
task_generatedObjs() started
obj/debug/res0.o obj/release/res0.o
obj/debug/res1.o obj/release/res1.o
obj/debug/res2.o obj/release/res2.o
.  release.bin
linkAction(targets:['release.bin'], file_dep:set(['obj/release/res2.o', 'obj/release/res0.o', 'obj/release/res1.o', 'obj/release/Main.o'])
g++: error: obj/release/res2.o: No such file or directory
g++: error: obj/release/res0.o: No such file or directory
g++: error: obj/release/res1.o: No such file or directory
##

**Comment by schettino72** [comment]
My conclusion is that this probably a `won't fix`. It is hard to be implemented in an efficient way, and this situation can be avoided by how the task creation is organized.

There is a note in the code about this:
https://github.com/pydoit/doit/blob/master/doit/control.py#L113

Need to make it clear in the docs.
