### ISSUE TITLE
New installation on ubuntu failed to run

### ISSUE THREAD

**Issue by oeway** [pydoit/doit#133]
Hi, I installed doit by clone the git repository, and then "python setup.py install", but when I type doit, it returns error:

```python
Traceback (most recent call last):                                                                          
  File "/usr/local/bin/doit", line 9, in <module>                                                           
    load_entry_point('doit==0.30.dev0', 'console_scripts', 'doit')()                                        
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 549, in load_entry_point    
    return get_distribution(dist).load_entry_point(group, name)                                             
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2542, in load_entry_point   
    return ep.load()                                                                                        
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2202, in load               
    return self.resolve()                                                                                   
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2208, in resolve            
    module = __import__(self.module_name, fromlist=['__name__'], level=0)                                   
  File "/usr/local/lib/python2.7/dist-packages/doit-0.30.dev0-py2.7.egg/doit/__init__.py", line 31, in <modu
le>                                                                                                         
    from doit import loader                                                                                 
  File "/usr/local/lib/python2.7/dist-packages/doit-0.30.dev0-py2.7.egg/doit/loader.py", line 10, in <module
>                                                                                                           
    from .task import DelayedLoader, Task, dict_to_task                                                     
  File "/usr/local/lib/python2.7/dist-packages/doit-0.30.dev0-py2.7.egg/doit/task.py", line 15, in <module> 
    from .dependency import UptodateCalculator                                                              
  File "/usr/local/lib/python2.7/dist-packages/doit-0.30.dev0-py2.7.egg/doit/dependency.py", line 8, in <mod
ule>                                                                                                        
    from dbm import dumb                                                                                    
ImportError: cannot import name dumb  
```

I found if I roll back:
```
 git checkout 9bf60efc8d7a3410caa97903e581c85c47450cf6
```
Then it worked.

So, I think there is something broken during update. Didn't have time to test other commits, hope someone can fix it. Thanks.

**Comment by schettino72** [comment]
doit master does not support python2 anymore. We need to change the `setup.py` to fail on installation and give a clear error message.

**Comment by GadgetSteve** [comment]
This solution states that the last version of doit supporting python 2.7 is version 0.29 - testing shows that due to changes in configparser the last version of doit supported on python 2.7 is version 0.27 please re-open.  

Also patch does not address documentation issues in doc\index.rst and doc\dictionary.txt plus appveyor.yml

**Comment by schettino72** [comment]
> testing shows that due to changes in configparser the last version of doit supported on python 2.7 is version 0.27

which changes on configparser? can you show me a traceback? Python 2.7 is on bugfix mode, so changes on it should not break previous releases of doit.

> Also patch does not address documentation issues in doc\index.rst and doc\dictionary.txt plus appveyor.yml

I will mention it on index only after I release 0.30 (sometimes I update the website before making a new release)

I guess you are mistaken about appveyor...

**Comment by GadgetSteve** [comment]
Sorry - appveyor line is commented out - I got the list of files that still mention python 2.7 with a grin command and didn't notice the `#` at the beginning of the line.

Python 2.7.12 on Windows 10
Testing 0.28
-------------
```
F:\toolbuild\doit>pip install doit==0.28
Collecting doit==0.28
  Downloading doit-0.28.0.tar.gz (213kB)
    100% |################################| 215kB 2.2MB/s
Requirement already satisfied (use --upgrade to upgrade): six in c:\python27\lib\site-packages (from doit==0.28)
Requirement already satisfied (use --upgrade to upgrade): configparser in c:\python27\lib\site-packages (from doit==0.28)
Building wheels for collected packages: doit
  Running setup.py bdist_wheel for doit ... done
  Stored in directory: C:\Users\Steve-Gadget\AppData\Local\pip\Cache\wheels\58\de\dd\aa06ed27347a7ccece7d657e7ef98a6c6f6e4b20c5a8cf91ea
Successfully built doit
Installing collected packages: doit
  Found existing installation: doit 0.29.0
    Uninstalling doit-0.29.0:
      Successfully uninstalled doit-0.29.0
Successfully installed doit-0.28.0

F:\toolbuild\doit>doit help info
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\doit.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\doit\__main__.py", line 8, in main
    sys.exit(DoitMain().run(sys.argv[1:]))
  File "c:\python27\lib\site-packages\doit\doit_cmd.py", line 58, in __init__
    ini_config = self.load_config_ini(config_filenames)
  File "c:\python27\lib\site-packages\doit\doit_cmd.py", line 71, in load_config_ini
    cfg_parser = ConfigParser(allow_no_value=True, delimiters=('=',))
TypeError: __init__() got an unexpected keyword argument 'delimiters'
```
Testing 0.27
-------------
```
F:\toolbuild\doit>pip install doit==0.27
Collecting doit==0.27
  Downloading doit-0.27.0.tar.gz (193kB)
    100% |################################| 194kB 1.2MB/s
Requirement already satisfied (use --upgrade to upgrade): six in c:\python27\lib\site-packages (from doit==0.27)
Building wheels for collected packages: doit
  Running setup.py bdist_wheel for doit ... done
  Stored in directory: C:\Users\Steve-Gadget\AppData\Local\pip\Cache\wheels\2c\13\4d\a5feceab96a3905b361e6ce7eed1be6bff92bf767304ebf34c
Successfully built doit
Installing collected packages: doit
  Found existing installation: doit 0.28.0
    Uninstalling doit-0.28.0:
      Successfully uninstalled doit-0.28.0
Successfully installed doit-0.27.0

F:\toolbuild\doit>doit help info
Purpose: show info about a task
Usage:   doit info TASK

Options:
``` 
etc.

Looking into the documents configparser in python 2.7 takes options such as delimiters in a dict not as a parameter. So it was a change in the way that configparser is created in doit in response to a python 2->3 change in configparser.

**Comment by GadgetSteve** [comment]
BTW - the warning does not come up when upgrading with `pip install --upgrade doit` - this is what caught me out.
It would be really helpful if there was a way in pypi to mark an existing release as not compatible with a version of python _so that 0.28 & 0.29 could be so marked_  but I have not been able to find one. The only thing that I can think of is branching off of the code at 0.27 - adding a warning that this is the last version to support python 2 and releasing as 0.29.1 so as to supersede 0.29 but that would be up to you. Then of course you would need to release 0.30 with all of the improvements included & which has the compatibility flags removed so pip 2 should ignore it.

**Comment by schettino72** [comment]
I guess your problem was an outdated version of `configparser` library (from pypi). Since python 2 is not supported anymore I dont think it is worth bothering about it.

If you want a fix for that: create a branch for a doit 0.29.1 release, with a pull request pinning the configparser version.

**Comment by GadgetSteve** [comment]
Checking configparser doesn't do it for me, I'll see about an updated version of 0.29 that works for python 2.7.11:
```
>pip install -U configparser
Requirement already up-to-date: configparser in c:\python27\lib\site-packages

>pip show configparser
---
Metadata-Version: 2.0
Name: configparser
Version: 3.5.0
Summary: This library brings the updated configparser from Python 3.5 to Python 2.6-3.5.
Home-page: http://docs.python.org/3/library/configparser.html
Author: Lukasz Langa
Author-email: lukasz@langa.pl
Installer: pip
License: MIT
Location: c:\python27\lib\site-packages
Requires:
Classifiers:
  Development Status :: 5 - Production/Stable
  Intended Audience :: Developers
  License :: OSI Approved :: MIT License
  Natural Language :: English
  Operating System :: OS Independent
  Programming Language :: Python
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.6
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: 3.5
  Topic :: Software Development :: Libraries
  Topic :: Software Development :: Libraries :: Python Modules
c:\Users\Steve-Gadget\Downloads>pip install -U doit
Collecting doit
  Using cached doit-0.29.0.tar.gz
Requirement already up-to-date: six in c:\python27\lib\site-packages (from doit)
Requirement already up-to-date: cloudpickle in c:\python27\lib\site-packages (from doit)
Requirement already up-to-date: configparser in c:\python27\lib\site-packages (from doit)
Building wheels for collected packages: doit
  Running setup.py bdist_wheel for doit ... done
  Stored in directory: C:\Users\Steve-Gadget\AppData\Local\pip\Cache\wheels\29\ec\aa\4263b95fa3320cdb8efcf32cfd5d0052390d0bc13349ef9d73
Successfully built doit
Installing collected packages: doit
  Found existing installation: doit 0.27.0
    Uninstalling doit-0.27.0:
      Successfully uninstalled doit-0.27.0
Successfully installed doit-0.29.0

>doit help
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\doit.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\doit\__main__.py", line 8, in main
    sys.exit(DoitMain().run(sys.argv[1:]))
  File "c:\python27\lib\site-packages\doit\doit_cmd.py", line 59, in __init__
    ini_config = self.load_config_ini(config_filenames)
  File "c:\python27\lib\site-packages\doit\doit_cmd.py", line 72, in load_config_ini
    cfg_parser = ConfigParser(allow_no_value=True, delimiters=('=',))
TypeError: __init__() got an unexpected keyword argument 'delimiters'
```

**Comment by schettino72** [comment]
well, the whole point on using a backport is to avoid this issues.

looks like for some reason you are not using the backport even if it is installed.
try this:

```
>>> import configparser
>>> configparser.__file__
```

the backport definitely supports `delimiter` parameter: https://bitbucket.org/ambv/configparser/src/78998f2ded2e840376adc712337545014fa9b622/src/backports/configparser/__init__.py?at=default&fileviewer=file-view-default#__init__.py-594

**Comment by GadgetSteve** [comment]
`import configparser; configparser.__file__;` returns the default path `c:\\python27\\lib\\site-packages\\configparser\\__init__.pyc`

but the help shows the signature as:
 `__init__(self, defaults=None, dict_type=<class 'collections.OrderedDict'>, allow_no_value=False)`

Checking on pip:
F:\toolbuild\doit>pip show configparser
---
Metadata-Version: 2.0
Name: configparser
Version: 3.5.0
Summary: This library brings the updated configparser from Python 3.5 to Python 2.6-3.5.
Home-page: http://docs.python.org/3/library/configparser.html
Author: Lukasz Langa
Author-email: lukasz@langa.pl
Installer: pip
License: MIT
Location: c:\python27\lib\site-packages
Requires:
Classifiers:
  Development Status :: 5 - Production/Stable
  Intended Audience :: Developers
  License :: OSI Approved :: MIT License
  Natural Language :: English
  Operating System :: OS Independent
  Programming Language :: Python
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.6
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: 3.5
  Topic :: Software Development :: Libraries
  Topic :: Software Development :: Libraries :: Python Modules

but a pip uinstall followed by a pip install clears the problem up - sorry for the noise!
