### ISSUE TITLE
Issues around text encoding.

### ISSUE THREAD

**Issue by FrankStain** [pydoit/doit#136]
Hey @schettino72 ! :)

I know that text encoding at python is a madness. But lets try to deal with next issues.
Currently i working on Windows OS with russian locale.Encoding of console is set to cp866. When i launch `chcp`, i see next text: `Текущая кодовая страница: 866`.

But if i try to execute next code:

``` .py
def task_LogChars() :
    return {
        'actions': [
            ( 'chcp' )
        ],
        'verbosity': 2
    }
```

next exception will be raised:

```
.  LogChars
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python34\lib\threading.py", line 920, in _bootstrap_inner
    self.run()
  File "C:\Python34\lib\threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python34\lib\site-packages\doit\action.py", line 172, in _print_process_output
    realtime.write(line)
  File "C:\Python34\lib\encodings\cp866.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-5: character maps to <undefined>
```

As i see, the instances of CmdAction receives no information about encoding of console, considering it will be 'utf-8'. After that, the localized string is wrongly decoded to 'utf-8' instead of 'cp866' ( at https://github.com/pydoit/doit/blob/master/doit/action.py#L143 ). At this moment string start contains wrong characters. At the end, writeing of this wrong string into console ( at https://github.com/pydoit/doit/blob/master/doit/action.py#L153 ) raises the exception.

So, i suggest one modification at https://github.com/pydoit/doit/blob/master/doit/action.py#L430

``` .py
    if isinstance(action, six.string_types):
        return CmdAction(action, task_ref, shell=True, encoding = sys.stdout.encoding)

    if isinstance(action, list):
        return CmdAction(action, task_ref, shell=False, encoding = sys.stdout.encoding)
```

Currently i can't be sure this code will work in all cases. I just don't know, how `runtime` and `capture` could be changed. But this code deals with exception from my example.
@schettino72 , what do you think about it?

**Comment by FrankStain** [comment]
Currently i had forced all my actions to explicitly use CmdAction. Just like that:
```.py
def task_LogChars() :
    return {
        'actions': [
            CmdAction( 'chcp', shell = True, encoding = sys.stdout.encoding )
        ],
        'verbosity': 2
    }
```
It solves the problem, but i see this approach as not clear.

**Comment by schettino72** [comment]
Sorry. I thought I had answered this before...

So using Gnome Terminal on linux, I could set the "Terminal Character Encoding" to CP866. And using the following sample Task.

```
import sys
from doit.action import CmdAction


def task_echo():
    return {'actions': [CmdAction('echo Текущая кодовая страница: 866',
                                  encoding=sys.stdout.encoding)]}
```

Without setting encoding explicitly I dont get an error, just garbled text:

```
.  echo
╨в╨╡╨║╤Г╤Й╨░╤П ╨║╨╛╨┤╨╛╨▓╨░╤П ╤Б╤В╤А╨░╨╜╨╕╤Ж╨░: 866
```

Explicitly setting the encoding makes no difference. I notice that if I just open a python terminal and check `sys.stdout.encoding`, python gives me `UTF-8`. So I am not even sure how to detect the real encoding being used by the terminal... any ideas.

And can you test again using latest master, I did some changes on this part since release 0.29.

**Comment by FrankStain** [comment]
Hey, @schettino72 :)
Sry for my silence. Currently i'm busy a lot...

My python (3.4) tells me `cp866` on checking the `sys.stdout.encoding`.
Currently i just can't change the environment and check this behaviour using your last code. But, i'll think about it in future.

Shortly what happens with text on my current machine (and other machines running russian windows) is looks like that. Let's open python in terminal, it's doesn't matter what encoding currently turned on.
```.py
>>> test_buffer = 'Текущая кодовая страница: 866'.encode( 'cp866' )
>>> test_buffer
b'\x92\xa5\xaa\xe3\xe9\xa0\xef \xaa\xae\xa4\xae\xa2\xa0\xef \xe1\xe2\xe0\xa0\xad\xa8\xe6\xa0: 866'
>>>
>>> test_buffer.decode( 'utf-8', errors='replace' )
'\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\u082d\ufffd\ufffd: 866'
>>>
>>>
>>> test_buffer.decode( 'utf-8', errors='replace' ).encode( 'cp866' )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\lib\encodings\cp866.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-5: character maps to <undefined>
>>>
```

After production in `cp866` encoding, the text has been returned from child process into 'doit' process. At this point 'doit' decodes it using ( 'utf-8', errors='replace' ) configuration. After that, wrongly decoded and broken text has been transferred into console output, where the `cp866` fails the encoding of it.

As i see, you have made a lot of changes in actions. I'll try test it as soon as i can.

And, by the way, thanks for your great work with doit! :)

**Comment by poliquin** [comment]
I think Python's solution to this is the [`locale` module](https://docs.python.org/3.6/library/locale.html)...

```python
import locale
locale.getpreferredencoding()
# 'UTF-8' for me
```
It's also possible to let the user use `locale.setlocale` in `dodo.py`, then call `locale.getlocale()` to return a language, encoding tuple...

```python
locale.getlocale()
# ('en_US', 'UTF-8') for me
```

**Comment by schettino72** [comment]
is this still an issue. Seems python3.6 there was some changes 
https://docs.python.org/3/whatsnew/3.6.html?highlight=encoding#whatsnew36-pep528

**Comment by FrankStain** [comment]
@schettino72 , hi there! :)

Such an old question. Frankly i thought this question was solved somehow already. Nope, looks like it is not an issue more.
Since switching to python 3.8 and 3.9 i have never facing this issue more.

Should i just close it now?

**Comment by schettino72** [comment]
haha, glad you still use doit :smile:
