### ISSUE TITLE
Print the result of a sh command twice when the command exits abnormally.

### ISSUE THREAD

**Issue by congeal** [pydoit/doit#140]
I call a shell command inside a task to decide pass or fail for the result that another task produces.
The shell command exits with nonzero exit code and prints some failure message if the decision is failure.
Doit prints the failure message that it captured when the task returns with the nonzero exit code, which leads to show the message TWICE when I set the verbosity level '2.'
I think that Doit should not print the captured message when the task failed and its verbosity level is higher than zero.

**Comment by schettino72** [comment]
fair enough. this is an issue since the first days of doit. you are the first to complain :smile: 

do you want give a try providing a patch? :grin:

**Comment by schettino72** [comment]
So sometimes I like the fact the error message is printed twice, once at real time and once again in the end. So lets add an option (non-default) that keeps the current behaviour. But by default if the output is already displayed in realtime it wont be repeated.
