### ISSUE TITLE
Add top level debug command

### ISSUE THREAD

**Issue by sean-abbott** [pydoit/doit#143]
it would be great to have a top level debug command that would dump the decision points / what was not "uptodate" so you could tell what had changed (or was missing) when tasks re-run when you weren't expecting them to.

**Comment by GadgetSteve** [comment]
@sean-abbott You could always try the combination of:

 - `doit list` - get a list of tasks
 - `doit info` _task_ - for each task get the dependencies, etc
 - `doit info -status` _task_ - for each task get what is out of date, etc

**Comment by schettino72** [comment]
@sean-abbott please dont send an email and then open a ticket with the same question. 
Thanks Steve answered you...

**Comment by sean-abbott** [comment]
For what it's worth, one was a question, the other was a suggestion. This
gets me about 80% of what I wanted, although I would suggest a call out in
the docs.
