### ISSUE TITLE
Error when using `pathlib.Path` to specify dependencies

### ISSUE THREAD

**Issue by DGrady** [pydoit/doit#145]
According to [the documentation](http://pydoit.org/tasks.html#file-dep-file-dependency), dependencies and targets can be specified either as strings or as instances of `pathlib.Path`. However, this appears to cause an error in the example below.

`dodo.py`:

```
from pathlib import Path

def task_one():

    inputpath = Path('data.txt')
    outputpath = Path('processed.txt')

    return {
        'file_dep': [inputpath],
        'targets': [outputpath],
        'actions': [['cp', str(inputpath), str(outputpath)]]
    }
```

Then on the command line:

```
% doit list
ERROR: one. file_dep must be a str got 'PosixPath('data.txt')' (<class 'pathlib.PosixPath'>)
```

**Comment by schettino72** [comment]
oops. this feature is available on master but not released yet.

**Comment by schettino72** [comment]
Sorry, the website should have been updated with that yet... http://pydoit.org/changes.html#unreleased
