### ISSUE TITLE
when run from a script / without a tty, verbose mode doesn't stream output

### ISSUE THREAD

**Issue by vikstrous** [pydoit/doit#148]
Let me know if you need a repro. I think it's pretty easy to reproduce.

**Comment by schettino72** [comment]
which version? or master?  there were quite a few changes in this code since last release.
on linux? or windows? or...

**Comment by vikstrous** [comment]
Example task:
```
def task_example():
    return {
        'actions': ['echo 1; sleep 1; echo 2; sleep 1; echo 3']
    }
```
Run with `doit -v 2 example`
OS: `Linux thisisfine 4.7.3 #1-NixOS SMP Wed Sep 7 06:35:12 UTC 2016 x86_64 GNU/Linux`
doit version: 0.29.0

**Comment by schettino72** [comment]
how do you test no TTY? I redirected output to a file and worked just fine:

```
(py35) /mnt/work/doit/dev$ doit -f bug148.py -v 2
.  example
1
2
3
(py35) /mnt/work/doit/dev$ doit -f bug148.py -v 2 > out.txt
(py35) /mnt/work/doit/dev$ cat out.txt 
.  example
1
2
3
```

**Comment by vikstrous** [comment]
I'm talking about stdin being a tty vs not a tty. If you run `sh -c "doit -f bug148.py -v 2"` that might work.

**Comment by schettino72** [comment]
works for me

```
$ sh -c "doit -f bug148.py -v 2"
.  example
1
2
3
```

**Comment by vikstrous** [comment]
Hmm. I can't find a good way to repro this without docker. If you run doit in docker without `-t`, it will not stream the output.

**Comment by schettino72** [comment]
i am not very familiar with docker... but if you cant reproduce without docker must be a docker problem :grin:

**Comment by vikstrous** [comment]
Okay, sorry, I figured it out. It was about output redirection.

If you run:

`sh -c "doit -f bug148.py -v 2 | tee /dev/null"`

you'll see that the output doesn't come out one line at a time, but all at once after 3 seconds.

**Comment by schettino72** [comment]
> If you run:

> sh -c "doit -f bug148.py -v 2 | tee /dev/null"

> you'll see that the output doesn't come out one line at a time, but all at once after 3 seconds.

No, for me it comes line by line. Maybe your shell (or whatever is running the doit script) is buffering it.

**Comment by schettino72** [comment]
By the way on master there is support to buffer by number of bytes instead of line based:  d58a73aaf6b01d7474a4923bba02fc02f0298547
