### ISSUE TITLE
Load sqlite3 module only as needed

### ISSUE THREAD

**Issue by TMiguelT** [pydoit/doit#153]
I'm in a very limited environment where I don't have python compiled with the sqlite3 headers.

Unfortunately, in [dependency.py](https://github.com/pydoit/doit/blob/master/doit/dependency.py#L20), the module is loaded unconditionally, so even if I set my backend to use json, python still crashes: 

Could we perhaps load the sqlite (and, I suppose, the dbm module) only if it's selected as a backend in [`get_backends()`](https://github.com/pydoit/doit/blob/master/doit/cmd_base.py#L356)?

**Comment by schettino72** [comment]
sure. Can you please provide a path?

**Comment by TMiguelT** [comment]
I'm happy to, I'm just not sure at which point in the code I should do the imports. Can you give me some pointers?
