### ISSUE TITLE
reporter: get info from tasks that were not selected for execution

### ISSUE THREAD

**Issue by SergeVL** [pydoit/doit#155]
I would like to make custom reporter which send somewhere progress report - percent of executed tasks.

And in **Reporter.add_failure**, **Reporter.add_success**, **Reporter.skip_uptodate**  and **Reporter.skip_ignore** could count passed tasks.

In **Reporter.initialize(self, tasks)** I can count all tasks. But problem is that I can't count tasks which will be passed throw all previous procedures
because run could be called with glob syntax like **doit create_file:file***

So is there a way to count planned tasks in Reporter.initialize method?
Or could you add to Reporter.initialize some additional info for that?

**Comment by schettino72** [comment]
> So is there a way to count planned tasks in Reporter.initialize method?

No. Because everything is decided on run-time. The best you could do would be to rely on something like a dry-run. But unfortunately doit still does not have a dry-run implementation. Once there was a pull-request on that but it was abandoned half way...

**Comment by SergeVL** [comment]
This will be possible if Runner will send to reporter task_dispatcher :

```
def run_all(self, task_dispatcher):
        """entry point to run tasks
        @ivar task_dispatcher (TaskDispatcher)
        """
        try:
            if hasattr(self.reporter, 'initialize'):
                #- self.reporter.initialize(task_dispatcher.tasks)
                + self.reporter.initialize(task_dispatcher)
            self.run_tasks(task_dispatcher)
        except InvalidTask as exception:
            self.reporter.runtime_error(str(exception))
            self.final_result = ERROR
        finally:
            self.finish()
        return self.final_result

```
and keep selected tasks in dispatcher:
```
class TaskDispatcher(object):
    def __init__(self, tasks, targets, selected_tasks):
        self.tasks = tasks
        self.targets = targets
        + self.selected_tasks = selected_tasks
        ...

```

**Comment by schettino72** [comment]
I need to check the code to understand what you are trying to do...
Easier if you create a pull request :grinning:

**Comment by SergeVL** [comment]
My problem is that not all tasks from task_dispatcher.tasks will be called to reporter one way or another.
Another way in adding to reporter one more handler **Reporter.skip_filtered**

```
def run_tasks(self, task_dispatcher):
        node = None
        while True:
            if self._stop_running:
                break
        
            try:
                node = task_dispatcher.generator.send(node)
            except StopIteration:
                break
            
            if not self.select_task(node, task_dispatcher.tasks):
                self.reporter.skip_filtered(node.task) # <- call here 
                continue
                
            catched_excp = self.execute_task(node.task)
            self.process_task_result(node, catched_excp)

```

**Comment by schettino72** [comment]
I am ok with this `skip_filtered`, just submit a pull request.

**Comment by schettino72** [comment]
I added `selected_tasks` to `initialize()` as you first asked.
Actually this `skip_filtered` doesnt make sense. because `select_tasks()` will never be called for those tasks...

**Comment by SergeVL** [comment]
Thanksю I wish you all the best.
