### ISSUE TITLE
file_dep must be a str got 'PosixPath'

### ISSUE THREAD

**Issue by TMiguelT** [pydoit/doit#157]
So the docs mention that you should be able to use pathlib instances: http://pydoit.org/tasks.html#file-dep-file-dependency. However when I tried that I got the error `file_dep must be a str got 'PosixPath('bam/HG002.bam')' (<class 'pathlib.PosixPath'>)`.

Is this a case of the docs being newer than the version of doit I have from pip (0.29.0)?

**Comment by schettino72** [comment]
> Is this a case of the docs being newer than the version of doit I have from pip (0.29.0)?

yes.

**Comment by schettino72** [comment]
just release doit 0.30

**Comment by TMiguelT** [comment]
Fantastic! I'll try it out
