### ISSUE TITLE
on absent status

### ISSUE THREAD

**Issue by SergeVL** [pydoit/doit#159]
calling **doit list --all --status** and there are task which never  running yet

File "/usr/local/lib/python2.7/dist-packages/doit/cmd_list.py", line 83, in _print_task
    line_data['status'] = self.STATUS_MAP[task_status]
KeyError: 'error'

must be:
line_data['status'] = self.STATUS_MAP.get(task_status)

**Comment by poliquin** [comment]
I thought I fixed this with PR #142. Are you using the latest version?
