### ISSUE TITLE
Support new file system path protocol from Python 3.6 (PEP 519)

### ISSUE THREAD

**Issue by Hinidu** [pydoit/doit#160]
Hello, @schettino72!
Using [PEP-519](https://www.python.org/dev/peps/pep-0519/) the support for `pathlib` can be generalized and made more idiomatic. I don't need it personally right now but it seems that the overall python ecosystem will use this protocol eventually.

**Comment by schettino72** [comment]
I am not clear on what should be done here. `file_dep` already support pathlib.Path, anything else to be done?

**Comment by schettino72** [comment]
Closing because not sure what should be done...

**Comment by Hinidu** [comment]
I'm too far from it right now so I don't remember too :laughing:
