### ISSUE TITLE
Crashes on Python 3.3 due to missing pathlib

### ISSUE THREAD

**Issue by Kwpolska** [pydoit/doit#161]
I tried switching Nikola’s doit requirement to `doit==0.30.0` for Python 3, but [it fails](https://travis-ci.org/getnikola/nikola/jobs/187164264) on Python 3.3 because `pathlib` is needed. This happens because pip does not notice the extra dependency. The correct way to do this is with [environment markers](https://www.python.org/dev/peps/pep-0496/). We use them in Nikola for doit (in requirements.txt):

```
doit>=0.28.0,<=0.29.0 ; python_version <= '3.3'
doit>=0.28.0 ; python_version >= '3.4'
```

That can also be used for platform checks (pyinotify/macfsevents).

**Comment by schettino72** [comment]
i didnt know about enviroment markers. nice...

I will prepare a patch and make a new release with the fix soon. thanks.

**Comment by Kwpolska** [comment]
There is an issue with environment markers currently, in that they don’t work everywhere. An alternate solution is to use extras_require in setup.py.

```py
setup(
    extras_require={
        ':python_version >= "3.4"': ['doit>=0.28.0'],
        ':python_version <= "3.3"': ['doit>=0.28.0,<=0.29.0'],
    }
)
```

**Comment by schettino72** [comment]
sorry for taking so long to look into this.
`doit` already correctly includes `pathlib2` from pypi as dependency when python3.3 is used.
you can check doit `setup.py`. Also doit test suite on travis includes python 3.3.

It seems that none of doit dependencies were installed. Not idea why, but not a problem with `doit`.

**Comment by Kwpolska** [comment]
It’s might be a problem with pip, but doit can easily work around it.

**Comment by schettino72** [comment]
what can be done to work around it?

**Comment by Kwpolska** [comment]
I’ll make a PR for this.

**Comment by schettino72** [comment]
i dont think changing anything in doit will help. pathlib is installed for me: https://travis-ci.org/pydoit/doit/jobs/202332901#L167

**Comment by schettino72** [comment]
ok. merged and released doit 0.30.1

I doubt this will fix your problem. anyway it looks better now :smile: thanks.

**Comment by Kwpolska** [comment]
Thanks for merging! Make sure to tag this release in git. We’ll see how this works when Travis CI finishes building Nikola.

**Comment by Kwpolska** [comment]
The build still fails with [no module named pathlib](https://travis-ci.org/getnikola/nikola/jobs/202363245#L1197), but [pathlib2](https://travis-ci.org/getnikola/nikola/jobs/202363245#L506) get installed. Is `pathlib2` the correct thing to install? Because your dev requirements [pull in `pathlib`](https://travis-ci.org/pydoit/doit/jobs/202361339#L244)…

**Comment by schettino72** [comment]
good catch... but pathlib2 is what i want: https://pypi.python.org/pypi/pathlib/1.0.1

**Comment by Kwpolska** [comment]
You linked to `pathlib`, which provides a `pathlib` package, and depend on `pathlib2`, which provides `pathlib2.py`.

**Comment by schettino72** [comment]
you are right. i am gonna fix it... thanks

**Comment by schettino72** [comment]
release 0.30.2 just using `pathlib` without the `2`.

**Comment by schettino72** [comment]
please let know the result either way.

**Comment by Kwpolska** [comment]
[It works.](https://travis-ci.org/getnikola/nikola/jobs/202374465)

Both releases are still untagged.

**Comment by schettino72** [comment]
great. thanks for the patience

it is tagged https://github.com/pydoit/doit/tags
