### ISSUE TITLE
max parallel execution for a task (or task-group)

### ISSUE THREAD

**Issue by karelv** [pydoit/doit#162]
When one has a several task with low cpu load, and several cpu intensive tasks, it makes sense to have 1 process for the cpu low load task (ex. download a file from internet), while 3 other processes are used for computing heavy stuf.

Is this a feature that is planned? Is it hard to add?

**Comment by schettino72** [comment]
please check #130. I guess that covers your use case.

**Comment by schettino72** [comment]
This comment https://github.com/pydoit/doit/issues/130#issuecomment-205029525 there are some pointers for an implementation.

**Comment by karelv** [comment]
It looks like it is, I will have look.
Thanks a lot!
