### ISSUE TITLE
'get_var' fails while the multiprocess execution if any task uses delayed creation.

### ISSUE THREAD

**Issue by FrankStain** [pydoit/doit#164]
@schettino72 , hey! :)

So, i found strange behaviour while trying to implement some stuff.

```.py
#! /usr/bin/doit -f
# -*- coding: utf-8 -*-

from doit import get_var
from doit import create_after

get_var( 'A', None )


def task_foo() :
  return {
    'actions': [ 'echo foo' ],
    'task_dep': [ 'bar' ],
  }
  
@create_after( executed = 'baz' )
def task_bar() :
  for i in range( 10 ) :
    yield {
      'name': 'bar_{}'.format( i ),
      'actions': [ 'echo bar_{}'.format( i ) ]
    }
    
def task_baz() :
  for i in range( 10 ) :
    yield {
      'name': 'baz_{}'.format( i ),
      'actions': [ 'echo baz_{}'.format( i ) ]
    }
```

This code works fine while being executed in single-process mode. But it fails in multi process mode.

```
/root>GetVar.py -n 2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/py3.4/lib/multiprocessing/spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "/py3.4/lib/multiprocessing/spawn.py", line 116, in _main
    self = pickle.load(from_parent)
  File "/root/GetVar.py", line 7, in <module>
    get_var( 'A', None )
  File "/py3.4/lib/site-packages/doit/doit_cmd.py", line 35, in get_var
    return _CMDLINE_VARS.get(name, default)
AttributeError: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/py3.4/lib/multiprocessing/spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "/py3.4/lib/multiprocessing/spawn.py", line 116, in _main
    self = pickle.load(from_parent)
  File "/root/GetVar.py", line 7, in <module>
    get_var( 'A', None )
  File "/py3.4/lib/site-packages/doit/doit_cmd.py", line 35, in get_var
    return _CMDLINE_VARS.get(name, default)
AttributeError: 'NoneType' object has no attribute 'get'
```

But if i remove the `create_after` decorator, all became works fine even in multi process mode. So, i found it ambiguous. I had seen no notifications in docs about such behaviour.

Can you confirm this is the doit error or not?
Currently i use the last (0.30.0) version of doit.

**Comment by schettino72** [comment]
Strange. It works for me... (on python3.5, linux)
I can not think how one thing would influence the other.

Which system is this?

**Comment by FrankStain** [comment]
@schettino72 , this code fails on Windows with python 3.4.

**Comment by madig** [comment]
I'm running into the same error on Windows 10 x64, Python 3.6.1 x64, doit 0.30.3, except that I'm not using decorators.
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python36\Lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python36\Lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "C:\UsersLocal\nikolaus.waxweiler\Development\...\dodo.py", line 28, in <module>
    "cert": get_var('cert', ''),
  File "c:\userslocal\nikolaus.waxweiler\development\...\venv\lib\site-packages\doit\doit_cmd.py", line 35, in get_var
    return _CMDLINE_VARS.get(name, default)
AttributeError: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "c:\userslocal\nikolaus.waxweiler\development\...\venv\lib\site-packages\doit\doit_cmd.py", line 167, in run
    return command.parse_execute(args)
  File "c:\userslocal\nikolaus.waxweiler\development\...\venv\lib\site-packages\doit\cmd_base.py", line 120, in parse_execute
    return self.execute(params, args)
  File "c:\userslocal\nikolaus.waxweiler\development\...\venv\lib\site-packages\doit\cmd_base.py", line 403, in execute
    return self._execute(**exec_params)
  File "c:\userslocal\nikolaus.waxweiler\development\...\venv\lib\site-packages\doit\cmd_run.py", line 252, in _execute
    return runner.run_all(self.control.task_dispatcher())
  File "c:\userslocal\nikolaus.waxweiler\development\...\venv\lib\site-packages\doit\runner.py", line 246, in run_all
    self.run_tasks(task_dispatcher)
  File "c:\userslocal\nikolaus.waxweiler\development\...\venv\lib\site-packages\doit\runner.py", line 449, in run_tasks
    proc_list = self._run_start_processes(job_q, result_q)
  File "c:\userslocal\nikolaus.waxweiler\development\...\venv\lib\site-packages\doit\runner.py", line 422, in _run_start_processes
    process.start()
  File "C:\Program Files\Python36\Lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Program Files\Python36\Lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Program Files\Python36\Lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Program Files\Python36\Lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Program Files\Python36\Lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe
```

The code in question is
```Python
CONFIG = {
    "cert": get_var('cert', ''),
    "tag": get_var('tag', ''),
}
```
Not using `get_var()` solves the problem.

**Comment by madig** [comment]
Parallel execution with subprocess result in the traceback above, using "threads" actually works. I immediately found a race condition in my code, too :) Aside from that, I finally have working parallelism on Windows with threads.

**Comment by schettino72** [comment]
Similar problem: https://github.com/pytorch/pytorch/issues/2341#issuecomment-346551098

On a Windows machine, you may need to wrap your multiprocessing code inside:
`if __name__ == '__main__'`

Can you try on `doit/__main__.py` moving the `main()` definition to be inside the `if` statement?

I just noticed original report is using `#! /usr/bin/doit -f`, are you using that also?
Can you test by executing from command line with standard `doit` command?

**Comment by schettino72** [comment]
Wondering if putting the main() definition inside the `if` will break setuptools entrypoint...

**Comment by schettino72** [comment]
Still thinking...

I guess the process created by multi-processing (a fork on linux but not a fork on windows), will try to re-execute this code dodo.py. The value actually wont be used...

So we would need to just make `get_var()` not raise an error and things should still work. Because in the actual task execution the value used will come from the main process. Can you test that?

**Comment by madig** [comment]
(Can't test until next week)

**Comment by Kwpolska** [comment]
> Wondering if putting the main() definition inside the if will break setuptools entrypoint...

Yes, it will.

Are you sure it will fix anything? The guidelne might have been misinterpreted:

> Safe importing of main module

> Make sure that the main module can be safely imported by a new Python interpreter without causing unintended side effects (such a starting a new process).

Source: https://docs.python.org/3//library/multiprocessing.html#the-spawn-and-forkserver-start-methods

**Comment by schettino72** [comment]
@Kwpolska thats was just me brainstorming without having a Windows system to test :stuck_out_tongue: 

Later I realised the problem is (probably) caused by `get_var()` not being safe to be executed (in the example it appears on module level). Because it relies on `doit` doing some initialization as the value is taken from command line...

I guess the best will be just make `get_var()` returns `None`. Or any other ideas?

**Comment by madig** [comment]
Just for reference, changing `__main__.py` to this:
```Python
# lazy way to ignore coverage in this file
if True:  # pragma: no cover
    if __name__ == '__main__':
        import sys
        from doit.doit_cmd import DoitMain
        sys.exit(DoitMain().run(sys.argv[1:]))
```
And invoking it directly rather than `doit` doesn't change anything.

I was however surprised to find that my wrapper method...
```Python
    def get_var(self, var, default):
        """Wrap doit.get_var calls, as several variables in doit aren't 
        initialized on import."""
        try:
            return doit.get_var(var, default)
        except AttributeError:
            return default
```
Still results in correct variable passing to subprocesses. I can use `-P process` on Windows without issue and `get_var()` variables passed in via the command line are picked up by tasks. Am I missing something?

**Comment by schettino72** [comment]
>  I can use -P process on Windows without issue and get_var() variables passed in via the command line are picked up by tasks. Shouldn't this blow up? 

No, doit actually sends the task metadata to subprocess. I.e. the subprocess does not execute the `task_xxx` functions. That's the reason you can not use closures as actions...

So I propose we do something like this:

```
def get_var(name, default=None):
    if _CMDLINE_VARS is None:
        return None
    return _CMDLINE_VARS.get(name, default)
``` 

Not returning the default. so it is still clear that the API is being used incorrectly.
I guess it should work on Windows as the only problem was the exceptions being raised,
as the actual value is NEVER used by doit.

@madig it would be great if you can test this and prepare a PR (with tests). thanks

**Comment by madig** [comment]
Just to understand this, do you know why this is a problem only on Windows? Windows-specific non-initialization of the variable?

Working on testing.

**Comment by schettino72** [comment]
yes, it is windows specific.

Windows has no "fork". 

On linux when a process fork it continues from where it were... copy the memory exactly as in the original process.

On windows, they start a new process from scratch. there is some magic involved, but for us what matters is that all modules are imported again on every process. I **guess** on windows `multiprocess` just try to load all modules present in the list of modules from the original process.

The issue is that `dodo.py` is loaded dynamically by doit application, and `get_var` requires some initialization.  So only on Windows multliprocess processes try to load `dodo.py` without proper initialization (parsing of command line arguments), then it  fails.

makes sense now?

**Comment by madig** [comment]
Ah, yes, that makes sense, thanks :) See the PR. Not sure if this is the optimal way to test it...
