### ISSUE TITLE
Python 3.4 semi-(un)supported

### ISSUE THREAD

**Issue by Gumnos** [pydoit/doit#168]
Attempting to install in a Py3.4 environment, I get

```
Collecting doit>=0.28.0; python_version >= "3.4" (from Nikola)
  Using cached doit-0.30.2.tar.gz
    Complete output from command python setup.py egg_info:
    error in doit setup command: Invalid environment marker: python_version <= "3.3"
```

Looking at `setup.py`, the `extras_require` forces the `python_version` to be <= 3.3 but further up in the file (in the **Classifiers** section) it suggests that versions <=3.5 should be supported.

This may be a simple update to that `python_version` line to set it to 3.6; or it might be that something changed that breaks things.

To replicate, it came from an attempt to install Nikola:

    $ mkvirtualenv -p python3 nikola
    (nikola)$ python --version
    Python 3.4.2
    (nikola)$ pip install --upgrade pip setuptools # local is outdated
    (nikola)$ pip install Nikola
    …
    Collecting doit>=0.28.0; python_version >= "3.4" (from Nikola)
      Using cached doit-0.30.2.tar.gz
        Complete output from command python setup.py egg_info:
        error in doit setup command: Invalid environment marker: python_version <= "3.3"

This is under Debian Stable on amd64, in case that makes a difference.

**Comment by Gumnos** [comment]
Deeper reading suggests that this was only trying to pull in the `pathlib` library if it was <= 3.3 so something is making it fail to find `python_version` as an "environment marker".

**Comment by schettino72** [comment]
It works on nikola master: https://travis-ci.org/getnikola/nikola/jobs/202687230

@Kwpolska any idea?

**Comment by Gumnos** [comment]
Is there anything beyond the `pip` and `setuptools` that would need to be upgraded to provide support for the `python_version` "environment marker"?

**Comment by Kwpolska** [comment]
That’s pretty crazy. This is what Nikola v7.8.3 is using:

```py
extras_require={
    ':python_version >= "3.4"': ['doit>=0.28.0'],
    ':python_version <= "3.3"': ['doit>=0.28.0,<=0.29.0'],
},
```

And this is doit v0.30.2:

```py
      extras_require={
          ':python_version <= "3.3"': ['pathlib'],
          ':sys.platform == "darwin"': ['macfsevents'],
          ':sys.platform == "linux"': ['pyinotify'],
      },
```

The two 3.3 lines look identical to me, and to diff.

Moreover, I cannot reproduce with Python 3.4.2 on Debian jessie x86_64 (without virtualenvwrapper, but that should not matter at all)

@Gumnos, could you try reporting that to setuptools?
