### ISSUE TITLE
Passing environment variables to CmdAction is broken

### ISSUE THREAD

**Issue by onnodb** [pydoit/doit#171]
It seems that [d58a73](https://github.com/pydoit/doit/commit/d58a73aaf6b01d7474a4923bba02fc02f0298547#diff-093aedc4845e9217a7220d8739946096R192) broke the ability to pass environment variables into `CmdAction`: if I now pass the `env` kwarg into the `CmdAction` constructor, this leads to a traceback:

`  File "/Users/onno/anaconda/envs/p3/lib/python3.5/site-packages/doit/action.py", line 204, in execute
    **self.pkwargs)
TypeError: type object got multiple values for keyword argument 'env'`

A minimal `dodo.py` to reproduce:

```python
from doit.action import CmdAction

def task_env_call():
    return {'actions': [CmdAction('echo Hi', env={'ENV_VAR', 'test'})]}
```

I guess that a workaround might be to prepend the environment variables to be set to the shell command string.

**Comment by schettino72** [comment]
Yes. broken :disappointed: 

> I guess that a workaround might be to prepend the environment variables to be set to the shell command string.

I would rather manipulate the `env` variable if it was passed. Something like:

```
kwargs = self.pkwargs.copy()
if self.buffering:
    if 'env' not in kwargs:
        kwargs['env'] = os.environ.copy() 
    kwargs['env']['PYTHONUNBUFFERED'] = '1'

        # spawn task process
        process = subprocess.Popen(
            action,
            shell=self.shell,
            #bufsize=2, # ??? no effect use PYTHONUNBUFFERED instead
            stdout=subprocess.PIPE, stderr=subprocess.PIPE,
            **kwargs)

```

Could please provide a patch including unit-tests?

**Comment by onnodb** [comment]
> I guess that a workaround might be to prepend the environment variables to be set to the shell command string.

I actually meant a temporary workaround for people using the broken version of Pydoit ;-)

As for actually fixing it: I'd cetainly be happy to provide a pull request. It's not something I have time for right away, but I'll see if there's some time on the weekend.

Thanks for the quick response!
