### ISSUE TITLE
`--seek-file` breaks `help` and `list` commands (possibly others)

### ISSUE THREAD

**Issue by wizeman** [pydoit/doit#174]
Hi,

It is mentioned in the following URL that the `--seek-file` argument can be used in an alias, to make `doit` search for the `dodo.py` file in parent directories:
https://groups.google.com/d/msg/python-doit/eKI0uu02ZeY/R7XdRaXoUvgJ

However, if I create such an alias, the `doit help` and `doit list` commands no longer work (possibly others too):
```
  $ alias doit='doit --seek-file'

  $ doit help
ERROR: Invalid parameter: "help". Must be a command, task, or a target.
Type "doit help" to see available commands.
Type "doit list" to see available tasks.

  $ doit list
ERROR: Invalid parameter: "list". Must be a command, task, or a target.
Type "doit help" to see available commands.
Type "doit list" to see available tasks.
```

**Comment by schettino72** [comment]
hummm. i see the problem... while the `list` command supports the `--seek-file` it expects something like `doit list --seek-file`. 

Maybe this alias is not a good advice... do you have any idea how to solve that?

**Comment by wizeman** [comment]
Why not parse command-line options with the built-in `argparse` module instead of `getopt`?

This would probably simplify option parsing code and would certainly (and extremely easily) allow you to add the `--seek-file / -k` option to all subcommands.

Python's documentation suggests to use `argparse` over `getopt` (see the note at the top or the much shorter argparse translation at the bottom):

https://docs.python.org/3/library/getopt.html

**Comment by schettino72** [comment]
`argparse` is not flexible/powerful enough.

I guess we could add `--seek-file` to be a `doit` parameter and then passing it to sub-commands.
This would fix the problem... also might apply this to other params.

This should not be hard. Do you want to give a try implementing that? :grimacing:

**Comment by schettino72** [comment]
I was thinking about this lately. I guess the best way would be to have this controlled by a shell Environment variable.

**Comment by wizeman** [comment]
@schettino72 Sounds good to me!

**Comment by balkierode** [comment]
Hi, I have created a pull request for the environment variable idea. Please take a look. 
#186 

Thanks,
Bala
