### ISSUE TITLE
database corruption

### ISSUE THREAD

**Issue by goerz** [pydoit/doit#182]
I'm using `doit` inside the Jupyter notebook. I frequently find that that dependency database becomes corrupted, producing a traceback like the following for any `doit` command:

    Traceback (most recent call last):
    File "/home/goerz/.conda/envs/default/lib/python3.6/site-packages/doit/doit_cmd.py", line 167, in run
        return command.parse_execute(args)
    File "/home/goerz/.conda/envs/default/lib/python3.6/site-packages/doit/cmd_base.py", line 120, in parse_execute
        return self.execute(params, args)
    File "/home/goerz/.conda/envs/default/lib/python3.6/site-packages/doit/cmd_dumpdb.py", line 48, in execute
        value_dict = json.loads(value_str.decode('utf-8'))
    File "/home/goerz/.conda/envs/default/lib/python3.6/json/__init__.py", line 354, in loads
        return _default_decoder.decode(s)
    File "/home/goerz/.conda/envs/default/lib/python3.6/json/decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    File "/home/goerz/.conda/envs/default/lib/python3.6/json/decoder.py", line 355, in raw_decode
        obj, end = self.scan_once(s, idx)
    json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 231 (char 230)

The `dumpdb` generates [some json output](https://gist.github.com/goerz/8cb4feb7e5360f0580f973fbb6e97238) before crashing.

I can fix this by deleting the database file in`~/.ipython/profile_default/db/.doit.db` (of course this means I lose the information about the job status). I haven't really been able to determine when exactly the corruption occurs. Since it seems from the location of the database file that only one database is used for *any* invocation of `doit` from the Jupyter notebook, my suspicion was that maybe it's when multiple notebooks are running at the same time. If this is indeed the case then (a) does `doit` implement proper locking of the database file if multiple invocations try to access it at the same time?, and (b) would it be possible to have a database file that is unique to a specific notebook?

**Comment by goerz** [comment]
I've started to define a `DOIT_CONFIG` dictionary in each notebook the specifies a unique database file, and I'll keep an eye on whether that solves the problem. However, I find it very hard to debug which database file is actually used, as `doit dumpdb` does not take into account any settings, and doesn't tell me which database file it's using (see my comment on #126)

**Comment by schettino72** [comment]
Which python version are you using? I notice you are using "dumbdb", maybe this implementation does not support concurrent access... How did you install your system? On linux you better use "dbm.gnu".

From your dump I could not really see the content that is causing trouble. It would be helpful if you:
- debug to see which task data was corrupted
- use python dbm to open your `.doit.db` and see what is actually store on it.

I guess the conclusion for this will just add a note in the docs warning the `dbm.dumb` does not support concurrent access.

**Comment by goerz** [comment]
I'm using Python 3.6, installed through the Anaconda Python distribution on a Linux system (Ubuntu 16.04). Indeed, it seems that Anaconda does not have `dbm.gnu` available (while the default system-Python-3.5 does). Maybe this is a problem similar to https://github.com/ContinuumIO/anaconda-issues/issues/1727. That being said, my expectation would be that `dbm.dump` is slow, but does not differ in functionality from `dbm.gnu` in regards to concurrency. If not, that would certainly warrant a bug report for anaconda.

In any case, I'll see if I can make the problem more reproducible and what stepping through with a debugger tells me.

**Comment by schettino72** [comment]
dumbdb does NOT support concurrent access. 
https://github.com/python/cpython/blob/3.6/Lib/dbm/dumb.py#L14

I wont fix this myself. just put a note on docs...

Maybe put a warning when doit is run? Although a warning might be useful it can also be very annoying.
