### ISSUE TITLE
Prevent doit 0.30 appearing in pip2 list --outdated?

### ISSUE THREAD

**Issue by tseemann** [pydoit/doit#185]
This may not really be an issue you can help with, but I thought I might ask anyway in case you know how to resolve it.

Is there anyway for `pip2` to know that 0.29 is that last Py2 version so it doesn't keep appearing to be out of date?   This is for an automatic updating system.

```
% pip2 list --outdated

Package Version Latest Type
------- ------- ------ -----
doit    0.29.0  0.30.3 sdist

% pip2 install doit

Collecting doit
    Complete output from command python setup.py egg_info:
    This version of doit is only supported by Python 3.
    Please use doit==0.29.0 with Python 2.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/linuxbrew/pip-build-MhatcW/doit/
```

**Comment by schettino72** [comment]
there is a solution.  see #181
there is more info there and i saw a pycon talk in the subject... the talk go into more details.

if you are willing to work on this i would push releases as soon as this is done.

**Comment by schettino72** [comment]
i did a 0.30.4 release using python requires, but to fix the issue i would really need to remove the existing 0.30 release. i guess this would cause more harm then solving your problem.

so, sorry. wont-fix

**Comment by Kwpolska** [comment]
I can’t see the new release on PyPI, although I got a notification from requires.io — what happened? Did you delete it?

**Comment by schettino72** [comment]
yes. i deleted. there was no gain from using it since it did not fix py2.7 issue. and it would cause some problem because setup.py would require pip 9. 

so i just deleted it. pip 9 will be required on 0.31
