### ISSUE TITLE
Please use `python3` instead of `python` on unittests

### ISSUE THREAD

**Issue by agustinhenze** [pydoit/doit#187]
When I run them on debian I got a lot of 
```
                            err_msg += ': ' + repr(orig_executable)
>               raise child_exception_type(errno_num, err_msg)
E               FileNotFoundError: [Errno 2] No such file or directory: 'python'
```

**Comment by schettino72** [comment]
hmmm. not sure how to handle this. simply changing 'python' to 'python3' will probably break in some other distribution...

seems not a problem on virtualenv... but still using 'python3' is debian thing.

**Comment by Kwpolska** [comment]
`python3` should exist [on all Unix systems](https://www.python.org/dev/peps/pep-0394/). That would break Windows, though. Perhaps you could use `sys.executable` if you’re launching from within Python?

**Comment by schettino72** [comment]
ok. thanks for the pointer. I will use `python3` on all shebangs.

For windows, lets see what happens...

**Comment by schettino72** [comment]
apart from tests it seems setuptools takes care of it. affects only tests and tests pass on windows. :smile:
