### ISSUE TITLE
Support decorator on task creator

### ISSUE THREAD

**Issue by nipunn1313** [pydoit/doit#188]
Eg

```
def my_decorator(func):
   ...

@my_decorator
def task_do_something():
    return {
        'actions': [...],
    }
```

Right, now, task_do_something will not collect. Not sure exactly why.

**Comment by schettino72** [comment]
please provide a complete example that reproduces the problem. Or a unit-test :grinning:

**Comment by nipunn1313** [comment]
I figured out how to repro. In the process, I found a derp with my source.
Closing this out. Apologies.

```
import contextlib
from doit.doit_cmd import DoitMain
from doit.cmd_base import ModuleTaskLoader

@contextlib.contextmanager
def my_decorator(func):
    def wrapper():
        print "Hi from wrapper"
        return func()
    return wrapper

@my_decorator
def task_hi():
    print "Hello world"

if __name__ == '__main__':
    ret = DoitMain(ModuleTaskLoader(globals())).run('')
```

Of course the issue here is that I have "contextlib.contextmanager" on my decorator.

Calling `task_hi()` explicitly, crashes since the code is busted (GeneratorContextManager is not callable).

Would have saved me if doit errored if there were globals labeled `task_*` that weren't functions, but I'd hardly call it a bug.
