### ISSUE TITLE
Tests are failing: [Errno 11] Resource temporarily unavailable

### ISSUE THREAD

**Issue by frenzymadness** [pydoit/doit#190]
Hello.

I have freshly installed doit from source code in the new virtual environment and when I try to run tests, some of them fails with error: [Errno 11] Resource temporarily unavailable

It seems that the error is caused by not-available database file in /tmp directory. I am using Python 3.6.2 on Fedora 26. 

I would like to fix it but I don't know how.

Outputs of tests and ;pip freeze` are attached.
[pip_freeze.txt](https://github.com/pydoit/doit/files/1249051/pip_freeze.txt)
[test_output.txt](https://github.com/pydoit/doit/files/1249052/test_output.txt)

**Comment by schettino72** [comment]
are you trying to execute tests in parallel?

**Comment by frenzymadness** [comment]
I am using command `pytest` nothing more. Is parallel execution enabled by default?

**Comment by schettino72** [comment]
> I am using command pytest nothing more. Is parallel execution enabled by default?

No. This error sometimes happen if you try to access the DBM file from 2 different processes.

- Do you have access to `/tmp`?  This tmp folder is picked by py.test...

- Are you running anthing else with `doit` while running the tests?

**Comment by schettino72** [comment]
have you solved this? works for me and continuous integration systems...
so assuming it is a problem on your setup. if not, please re-open.

**Comment by frenzymadness** [comment]
Hello.

Sorry for the delay. I don't know where the problem comes from so I am attaching console log from my session. You can see cloning of git repo, virtualenv creating, building and installing of doit, installing pytest and mock and then testing.

As you can see at the end, I have RW rights for folders where the pytest store testing databases and it can create the whole directory structure.

I am using Python 3.6.2.

**Comment by frenzymadness** [comment]
[console_recording.txt](https://github.com/pydoit/doit/files/1256485/console_recording.txt)

**Comment by schettino72** [comment]
you need to install all development dependencies...

instead of `pip install pytest`, you should run `pip install -r dev_requirements.txt`.

**Comment by frenzymadness** [comment]
```
$ pip freeze
cloudpickle==0.4.0
configclass==0.1.0
coverage==4.4.1
doit==0.31.dev0
doit-py==0.4.0
mergedict==0.2.0
mock==2.0.0
pbr==3.1.1
py==1.4.34
pyflakes==1.6.0
pyinotify==0.9.6
pytest==3.2.1
pytest-ignore-flaky==0.1.1
singledispatch==3.4.0.3
six==1.10.0
```

Installed but with the same result :(

It is not that big deal for me, but without working tests, I cannot contribute :(
