### ISSUE TITLE
interpolate `%(changed)s` in action string even if it is empty list

### ISSUE THREAD

**Issue by vlcinsky** [pydoit/doit#194]
Action string may include `%(dependencies)s`, `%(targets)s` and `%(changed)`.

The values of variable `dependencies`, `targets` and `changed` are provided as strings from respective lists separated by a space.

In case of `changed`, it may happen, that when the value is `None`, the value for `changed` is not set in dictionary and string interpolation using `%(changed)s` will fail with KeyError due to missing keyword.

See the line: 
https://github.com/pydoit/doit/blob/master/doit/action.py#L273

Proposal: in case of `None` (no changed input files), interpolate `%(changed)s` by empty string. This will make the behaviour consistent with other two keywords and more stable.

**Comment by schettino72** [comment]
Agree.

**Comment by schettino72** [comment]
How to reproduce this problem?
The problem is that `changed` is `None` it means it was not initialised (you did not call `get_status()`).

**Comment by schettino72** [comment]
I guess you got this problem by using doit internals without doit command...
So, I added an `assert` to make sure the API is being properly used.

**Comment by schettino72** [comment]
Actually I will revert this change... The problem is that `doit clean` also uses `expand_args` but `changed` is not computed. So it will still raise an exception if you try to use `changed` where it is not supported.
