### ISSUE TITLE
specify target of a DelayedTask on command line

### ISSUE THREAD

**Issue by schettino72** [pydoit/doit#20]
Since not all tasks are created before execution starts, it is required some special handling for target names of targets that have not been created yet.

See discussion on https://github.com/getnikola/nikola/issues/1562#issuecomment-70836094

General idea is that if a target is not found, before raising an error to the user try to load DelayedTasks (as done by command list) to look for the given `target` name.

Some considerations:

 1) as of now a DelayedTask creates an implicit `task_dep` for the task given in it's `executed` param. But this `task_dep` is not preserved when the DelayedTask is re-created. It should not only be preserved but all created tasks should include this `task_dep` because the guarantee that the dependent task was already executed wont exist anymore!

2) if the selected tasks for execution includes know tasks and targets they should be executed **before**, any DelayedTask is loaded to look for an unknown `target`. This will ensure that same command line will work nicely even if it is on its first execution.

**Comment by felixfontein** [comment]
Re 1): very good point.

Re 2): I guess one exception is that one of these tasks depends on a DelayedTask. So something like:
  - first determine which of the tasks and targets specified on the command line (or in ```default_tasks```) is not delayed; start executing as if the command line only containes these;
  - if during execution of these and their prerequisites one of the "missing" tasks/targets shows up, also make sure it and its prerequisites is executed;
  - finally, if all tasks are executed but some tasks/targets haven't been found, begin loading DelayedTasks until something is found (if yes, continue with it, etc.);
  - when everything specified on the command line is done, stop;
  - if doit runs out of DelayedTasks before this happens, terminate with error (as before).

Is this more or less what you meant?

**Comment by schettino72** [comment]
yes. thats it. 

Lets use the same dodo.py file as example to test this feature. https://github.com/pydoit/doit/blob/master/doc/tutorial/delayed.py should be good enough.
