### ISSUE TITLE
Make Open Collective public

### ISSUE THREAD

**Issue by schettino72** [pydoit/doit#200]
- [x] write Open Collective page
- [x] replace doit website (right-side bar) asking for donors/sponsors

**Comment by schettino72** [comment]
@vlcinsky we should also add some info about given weekly updates about what has been done. 
Maybe use twitter for that.

**Comment by vlcinsky** [comment]
@schettino72 I have updated opencollective page with the text proposed yesterday.

You are right, we shall report progress somehow. On the other hand I wonder, how to report progress in such a way, it does not consume too much time we should put into work on the doit itself. Personally I would prefer to report once a month or two, possibly starting with a bit higher frequency (like once in two weeks for first two month).

Options I am aware of are:
- twitter
- wiki page on Github, best with some automated statistics of issues and pull requests closed
- blog, possibly with tags as "maintenance", "docrefactoring", "statusreport"
- facebook
- linkedin

Personally I am in favour of a blog as in long term it can show we are really progressing and people visiting it later on can learn a lot. Twitter, facebook and linkedin allow subscription to news, but mostly just confuse people with irrelevant content.

Maybe we could set up a blog (I can provide solution we use for http://blog.tamtamresearch.com/ which is based on static files in git) and publish links to updates on twitter and facebook.

**Comment by schettino72** [comment]
I was thinking about twitter because they are very short :grin: 
dont take much time. just a quick update with links to issues/PR.
nothing fancy.

**Comment by schettino72** [comment]
Cool. I would just suggest one tiny change:

> can already test existing power of the tool.

change ~test~ to `use`.

**Comment by vlcinsky** [comment]
Fixed. Plus I pruned the text to make it shorter.

Remaining issues are:
- set up personal profile on opencollective for vlcinsky
- think, if we can define our promises better. Maintenance in long term seems fine to me. But with documentation we can probably set clear goal and define fixed amount of money to achieve it.
