### ISSUE TITLE
`doit.cfg` configuration parameters name should be visible on `doit help`

### ISSUE THREAD

**Issue by vlcinsky** [pydoit/doit#202]
Playing with multiple dodo.py files I searched for an option to configure the file name (as with `$ doit run -f things.py`).

`doit.cfg` seemed to be the way, but with:

```ini
[GLOBAL]
file = things.py
```
it had no effect and `doit` complained about problems to locate `dodo.py`.

**Comment by schettino72** [comment]
you need to use `dodoFile` not just `file`. see here: https://github.com/pydoit/doit/blob/master/doit/cmd_base.py#L187

i am pretty sure this is documented somewhere that you need to use the `name` parameter... but its horrible that you need to find the source code to see where it is defined.

**Comment by vlcinsky** [comment]
I added placeholder into documentation draft for these options: https://github.com/pydoit/doit-tmp-doc/commit/fc13affa93cf91ae047b0c5dc187393dfdd8f3dd

Now I know, where to search for the keywords and section names.
