### ISSUE TITLE
Allow configuring location of `dodo.py` file by environmental variable

### ISSUE THREAD

**Issue by vlcinsky** [pydoit/doit#203]
Something like:
```bash
$ export DOIT_GLOBAL_FILE=alter.py
```
should affect `doit` as if called:
```bash
$ doit run --file alter.py
```

At the same time, it priorities shall be clarified, as there are multiple places, where these options may be set:

- command line option
- env. variable
- doit.cfg

(dodo.py is not relevant in this case)

**Comment by schettino72** [comment]
this is now trivial to implement. just add an `env_var` to the param definition. see: https://github.com/pydoit/doit/commit/16560b255e059fbf8aa3c3e1aa7b982069cd0229

not properly documented...

**Comment by vlcinsky** [comment]
I will take care of describing existing options in updated doc. Placeholder is already there.

It is likely to generate more requests of these types, if we have clear design decision where and how the variables are to be used, it could be easy to remember.
