### ISSUE TITLE
Inconsistent expected position of command wide command line options (`-k`, `-f`)

### ISSUE THREAD

**Issue by vlcinsky** [pydoit/doit#204]
`doit` has couple of subcommands with respective options.

On the other hand, there are options which are common to all of them, especially when related to location of `dodo.py` file.

Trying to use `dodo.py` located in parent directory (with no `dodo.py` in current one):

```bash
$ doit -k
.  sphinx
Running Sphinx v1.6.4
...
build succeeded.

$ doit -f ../dodo.py 
.  sphinx
Running Sphinx v1.6.4
...
build succeeded.
```
This works fine.

However, trying to call other commands (such as `list`) starts complaining:
```bash
$ doit -f ../dodo.py list
ERROR: Invalid parameter: "list". Must be a command, task, or a target.
Type "doit help" to see available commands.
Type "doit list" to see available tasks.

$ doit -k list
ERROR: Invalid parameter: "list". Must be a command, task, or a target.
Type "doit help" to see available commands.
Type "doit list" to see available tasks.
```

If an option is used after subcommand, all runs well:

```bash
$ doit list -f ../dodo.py
spell    spell checker for doc files
sphinx   build sphinx docs

$ doit list -k
spell    spell checker for doc files
sphinx   build sphinx docs
```

Expected behaviour:

Whichever option may be considered global (namely `--seek-file/-k` and `--file/-f` related to which `dodo.py` file to use) shall be allowed before subcommand is called.

This way it is easy to repeate calls to different subcommands and edit only final part of command line.

**Comment by schettino72** [comment]
`-f` is not really global although used by most commands...

Although I would agree that would be nice to have those accepted in both positions.

**Comment by vlcinsky** [comment]
(I thought I have already written this comment in past)

doit help shows set of supported commands:

	$ doit help
	doit -- automation tool
	http://pydoit.org

	Commands
	  doit auto              automatically execute tasks when a dependency changes
	  doit clean             clean action / remove targets
	  doit dumpdb            dump dependency DB
	  doit forget            clear successful run status from internal DB
	  doit help              show help
	  doit ignore            ignore task (skip) on subsequent runs
	  doit info              show info about a task
	  doit list              list tasks from dodo file
	  doit reset-dep         recompute and save the state of file dependencies without executing actions
	  doit run               run tasks
	  doit strace            use strace to list file_deps and targets
	  doit tabcompletion     generate script for tab-completion

	  doit help              show help / reference
	  doit help task         show help on task dictionary fields
	  doit help <command>    show command usage
	  doit help <task-name>  show task usage

To me it seems, all are dependent on where dodo file is present. Maybe `doit help` and `doit help <command>` are exceptions.

## Problems with bash alias

Trying to set up alias for my dodo file I failed as alias does not support parameters. It in most cases allows adding arguments after commands and arguments at alias but this is where we get short with `doit`, which currently requires arguments as `-f` to be at the end and all the `list`, <task-name> etc. must precede it.

I managed with using function instead of alias:

	function donet() {
	    (cd ~/devel/pydoit/samples/nmcli && doit $*)
	}
