### ISSUE TITLE
Problems to use env var `DOIT_SEEK_FILE`

### ISSUE THREAD

**Issue by vlcinsky** [pydoit/doit#206]
Trying to use env variable `DOIT_SEEK_FILE` does not work for me.

Tried values such as "true", "True", "on", "1" as in:
```bash
$ export DOIT_SEEK_FILE=on
```
but the call:
```bash
$ doit list
```
still complains about problems to find `dodo.py`.

A call:
```bash
$ doit list -k
```
works well.

**Comment by schettino72** [comment]
are you using master? this feature has not been released yet.

**Comment by vlcinsky** [comment]
Bingo. With dev version from master it works for me.

Sometime I use Click for building CLI. The use of environment variables is well organized there, see http://click.pocoo.org/6/options/#values-from-environment-variables

Before releasing `doit` supporting envvar `DOIT_SEEK_FILE` it would be nice to check, is similar concept of using envvars helps `doit`. It could end up having nice systematic support for env vars in all options in `doit`.

I am by no way proposing nor discouraging use of Click, it is just a hint.

This issue seems to be resolved to me.
