### ISSUE TITLE
Clean Command Dependency Problems

### ISSUE THREAD

**Issue by leftink** [pydoit/doit#209]
There were two problems I came across with the clean command:
1. '-c' option doesn't pick up task dependencies where the target of one task is a file dependency of another task.
2. The clean execution order can be incorrect if more than one task has a dependency on the same task.

Below is a tarball of a simple example project that demonstrates the issues.
[doit.tar.gz](https://github.com/pydoit/doit/files/1356573/doit.tar.gz)

There are 4 tasks and 1 group task.

## Tasks:
**my_grp**:   Group task for ['tst', 't2']
**tst**:  Creates a file, task_dep for ['setup']
**t2**:   Creates a file, "inferred" task_dep for ['t1'] due to target of 't1' used as a file_dep
**t1**:   Creates a file, task_dep for ['setup']
**setup**:  Creates the output directory where all targets are stored

DOIT_CONFIG has {'default_tasks': ['my_grp']

After running doit on the dodo.py file all tasks are executed, but when I dry-run or even run doit clean things just seem wrong.

## Clean Options:
1. doit clean -n [-c]
   1. Should clean default tasks and dependencies
   2. Cleaned Tasks (in order): ['setup', 't2', 'tst']  **WRONG**
      1. Wrong order:  'setup' should have been last
      2. Missing task 't1'
2. doit clean -n tst
   1. Should clean 'tst' only
   2. Cleaned Tasks (in order): ['tst'] **GOOD**
3. doit clean -n -c tst
   1. Should clean 'tst' and dependencies
   2. Cleaned Tasks (in order): ['setup', 'tst']  **WRONG**
      1. Wrong order:  'setup' should have been last
4. doit clean -n -c t2
   1. Should clean 't2' and dependencies
   2. Cleaned Tasks (in order): ['t2']  **WRONG**
      1. Missing task 't1' and task 'setup'
5. doit clean -n -c t1
   1. Should clean 't1' and dependencies
   2. Cleaned Tasks (in order): ['setup', 't1']  **WRONG**
      1. Wrong order:  'setup' should have been last
6. doit clean -n -a
   1. Should clean all the tasks
   2. Cleaned Tasks (in order): ['setup', 't1', 't2', 'tst']  **WRONG**
      1. Wrong Order: 't2' and 'tst' should be first and 'setup' should be last
      2. Much like the implied '-c' when using default tasks, it seems like -a should also clean based on dependency order, i.e. implied '-c'
7. doit clean -n -a -c
   1. Should clean all the tasks with dependency order
   2. Cleaned Tasks (in order): [ 't2', 'tst', 'setup', 't1']  **WRONG**
      1. Wrong Order: 'setup' should be last

## Code
I haven't had a chance to analyze all the code yet, but what I have found revolves around the `to_clean.reverse()` processing.  First, before this line, the to_clean list needs to be filtered to remove duplicate tasks, but maintain order of first occurance, e.g. for python 3.6+ `to_clean=list(dict.fromkeys(to_clean))`.  May be able to do the same with an OrderedDict for other versions of python.  This will address attempt (7) above.  Another problem is it seems based on the path taken to get the to_clean, the list is already reversed in some instances.  Lastly, `tasks_and_deps_iter()` doesn't seem to be working correctly to pick up the implied task dependencies like those between 't1' and 't2'.

**Comment by schettino72** [comment]
Thanks for detailed report.

Oh shit. this clean ordering is completely broken. My conclusion was:

- the `to_clean.reverse()` is plain wrong and should be removed.

- the implicit dependencies are missing need to use `control.py:TaskControl.set_implicit_deps()`

- `tasks_and_deps_iter` is not good enough when `clean_list` has more then one element.
  I though about an algorithm to solve it, but a bit complex. easier to write code then explain in words...

---------

I guess first step is to write unit-tests that cover all the cases. Note that currently the tests are making sure the order is wrong :( , so they need to be re-written.

**Comment by leftink** [comment]
One thing I was trying look for was a generator, that given the tasks and their execution dependencies would return the tasks to be executed in the correct order.  From that, the reverse order would be the proper clean order.

It seems like you sort of have this, i.e. the TaskDispatcher, but it has more functionality to ensure tasks are executed before returning more tasks.

If that functionality was split into two generators, with the first generator being used to purely create the task execute order and always returns the next task, i.e. no state information, then the TaskDispatcher could wrap the generator and only pull new tasks when required and return the appropriate state information as it does today.

Then the execution order generator could be used by the clean command to get the proper clean order.

Just a thought.

**Comment by schettino72** [comment]
Not following you 100%. Anyway look at the `auto` command. It has some functionality to get the whole dependency tree without executing the tasks. That might be what you are looking for.

**Comment by leftink** [comment]
I looked at the `auto` command and unless I am missing something, it is dealing with the dependency tree the same way `clean` was, i.e. using `tasks_and_deps_iter()` which has its problems for getting the full list.

What I was trying to get at with my previous comment was the `run` command seems to have a mechanism for getting the full list of tasks to execute and in the proper order.  If I am reading the code correctly this is handled with `TaskControl()`.  After the list is "processed", a "dispatcher" is created an given to the "runner".

I had initially tried to fix the `clean` functionality by creating a `TaskControl` and the iterating over the dispatcher to get a list.  The thought being this would give me a full list of tasks to execute and since I needed to do a clean, reverse that list and run the clean on the reversed order.  That failed, because when iterating over the dispatcher, the dispatcher seems to track the state of the tasks, i.e. it sometimes return strings for the runner to use and not just a task.

So all I was suggesting in my previous comment was if the functionality was split into two generators, then the generator that creates the list of tasks and dependency order could be used by all commands.  The `run` command would then be updated to something like:

control = TaskControl() -> control.process() -> tg = control.task_generator() -> control.task_dispatcher(tg)

The task_generator() would just return the Task objects to execute in the proper order.  The task_dispatcher would behave as before, but when needing a "task" to return, would pull from "tg".

**Comment by schettino72** [comment]
> I looked at the auto command and unless I am missing something, it is dealing with the dependency tree the same way clean was

oh, sorry. I mislead you.

> The task_generator() would just return the Task objects to execute in the proper order. The task_dispatcher would behave as before, but when needing a "task" to return, would pull from "tg".

I dont think this approach would work. when you run you can start the processing from any task and you are guarantee that you will execute all the tasks from the sub-tree before it. 

If you want to reverse it you would really need to reverse all task_dep otherwise you will not know for sure what is above it. I think the best solution is to just build the whole dependency tree. It is not that trivial... I guess we will need to write a *new* TaskControl for the `clean` command.

I dont think the core processing of TaskControl will be useful and it is already quite complex code, so I definitely dont want to modify it for this use-case. Unless you prove me your approach works :grimacing:

**Comment by leftink** [comment]
You are the expert.  Every time I try to deep-dive and understand all the dependency stuff I walk away with a headache.  :rofl:

**Comment by schettino72** [comment]
Yes, I myself have some problems after a years I wrote it, it is a complex logic...
I think there are a lot of code comments, but let me know if you any specific questions.
I will not have time to look at this issue this month, will do when i have time.

**Comment by leftink** [comment]
Another example of a clean issue:
[dodo.py.gz](https://github.com/pydoit/doit/files/1387540/dodo.py.gz)

This example is simple and demonstrates that too much is getting cleaned.

It is creating a directory structure, with a task creating each level of the full path.  The intent is to be able to "clean" at any level.

1. doit clean -n wd:out:sub1:sub2:sub3
  1. Should clean only the task specified
  2. Cleaned Tasks (in order): [wd:out:sub1:sub2, wd:out:sub1:sub2:sub3] WRONG
    1. Too many levels cleaned
    2. The issue is line 92 of cmd_clean.py `to_clean.extend(subtasks_iter(tasks, task))`.
      1. It looks like this needs to be protected to only do this if the task is a group task, or the `subtasks_iter()` needs to check the task since the function is purely pulling task_dep which does not mean a sub-task if my understanding is correct.

**Comment by schettino72** [comment]
@leftink I basically re-wrote the clean command. Everything should work now the way you expected :grinning: Let me know I missed anything.

Also note that I fixed the problem with sub-tasks. I removed the attribute `Task.is_subtask` and added `Task.subtask_of` where the value is a string with the name of task to which this sub-tasks belongs to.
