### ISSUE TITLE
Publish doit docs on readthedocs

### ISSUE THREAD

**Issue by vlcinsky** [pydoit/doit#212]
Currently doit does not seem to have documentation built by, and more importantly available via readthedocs.

Having docs available on readthedocs gives user an advantage of getting it in preferred format (mostly html.zip, sometime pdf and sometime epub) and use it conveniently without accessing Internet (great in aeroplane, train etc.).

Consider publishing doit docs via readthedocs.

**Comment by vlcinsky** [comment]
I made a quick test with temporary documentation:
http://doit-tmp-doc.readthedocs.io/en/latest/index.html

and it works well. The only problem I have found is that it does not render images generated using PlantUML, but this is not relevant for existing stable documentation (and is not really required for new one, but I will try to resolve that).

**Comment by schettino72** [comment]
I do NOT want to use readthedocs.

- having the docs in 2 different places is a bad idea
- we already have a continuous integration to update the docs
- i dont like the fact they place ads in the documentation 
- once I tried i had some problems converting my templates

I can only see one advantage that is versioned docs. but I dont think that is important for doit.

**Comment by schettino72** [comment]
oh. and about DF and zip. I guess that could be easily be added to our CI.

When **I** want offline docs for any python project. 
I download the soure code and generate the docs.
I would think developers dont like reading through PDF but thats probably just me :grin:

**Comment by vlcinsky** [comment]
After some testing I agree, your arguments sound also very strong.

ReadTheDocs is somehow broken, e.g. it reports creation of ZIP and ePub files, but they are missing in Download section as [reported](https://github.com/rtfd/readthedocs.org/issues/3166).

ReadTheDocs supports publishing docs on other domains (that is what I understood), but let's skip it.

I am closing this issue.

**Comment by saimn** [comment]
> ReadTheDocs supports publishing docs on other domains (that is what I understood).

Yes (just to confirm - rtd is a great project but you are free not to use it).

**Comment by tom-varga** [comment]
I find it significantly easier to search for something in a pdf than docs
spread across many web pages.
So, I vote for supporting a pdf version of the docs too.

**Comment by vlcinsky** [comment]
@tom-varga follow the issue #214 where is the PDF requirements present.
