### ISSUE TITLE
Consider using StackOverflow for publishing "How To" and promoting  `doit`

### ISSUE THREAD

**Issue by vlcinsky** [pydoit/doit#213]
Current situation:
- there are few (not many) questions on StackOverflow related to doit. None of them is tagged with `doit`.
- StackOverflow is used by many developers as source of answers and is also very easy to use (add a question, edit it, answer ...)
- it allows for great cooperation with any contributor
- [Asking a question and answering it by one user is considered fine](https://meta.stackexchange.com/questions/17845/etiquette-for-answering-your-own-question) as it increase information on the site in form of question and answer

Options for promoting `doit` (thus serving potential users better) are:
- add properly selected tag (either `doit` or `pydoit`, I am not sure at the moment)
- review existing questions and add the tag to those, which are really related to doit
- publish "how to" information using question to state the problem and answer as the instruction how to do that.

When is this question resolved?
- either decide to reject this idea or consider it irrelevant as doit issue
- or fix the tags for existing questions and add at least three How to questions and answers.

Personal note: The only issue I have with this idea is that I made a [promise](https://stackoverflow.com/users/346478/jan-vlcinsky) to my colleague not to log into StackOverflow until I complete one task which awaits my capacity for longer time. But this issue shall be resolved in some time.

**Comment by schettino72** [comment]
Cool. i like stackoverflow. It could be "officially" advertised as a place to ask questions.
I would go for the tag `pydoit`. I tried to create a tag before but i dont have enough reputation...

**Comment by vlcinsky** [comment]
Nice. 

Regarding tags, I was thinking about `python` and `doit` as this is what people are likely to enter because the tool is now known as `doit` rather than `pydoit`. I would prefer to keep the name `doit` but we might find good reason to change it.

There shall be no problem with reputation, my current one is around 23700 on StackOverflow.

**Comment by schettino72** [comment]
ok. so lets go for tag `doit`.

**Comment by schettino72** [comment]
I added `doit` tag on one question[1]

[1] https://stackoverflow.com/questions/34957460/python-doit-use-arguments-in-dependent-tasks

It is waiting for a peer-review. Anyone? :grimacing:

**Comment by schettino72** [comment]
Created tag: https://stackoverflow.com/tags/doit/info

It seems I dont have enough privilege to edit the "tag wiki" :-1:
