### ISSUE TITLE
Unable to create a Delayed Task Creator by yielding a task dictionary

### ISSUE THREAD

**Issue by leftink** [pydoit/doit#217]
I realize this is not currently supported in the code, but I couldn't see any reason why it couldn't be supported.

Currently, it looks like Delayed task creation can only be accomplished by decorating a function as part of a module/dodo.py file.

I am however integrating doit into an application with a custom task loader.  As such, the way things are organized, the structure of the code is a top function yielding tasks or other generators to the custom task loader so in order for me to have a Delayed Task creator is to yield it back with other tasks.

Looking at the code, it appears the only thing that is preventing me from accomplishing my goal, is that generators can only yield task dictionaries and the ***ONLY*** attribute not defined in the valid_attrs for a task is the loader.

Based on my limited understanding of the code, if the key 'loader' was added to the valid_attr list then what I am trying to do would work.

A simple example:
```python
# example.py
import glob

from doit import create_after

@create_after(executed='early', target_regex='.*\.out')
def task_build():
    for inf in glob.glob('*.in'):
        yield {
            'name': inf,
            'actions': ['cp %(dependencies)s %(targets)s'],
            'file_dep': [inf],
            'targets': [inf[:-3] + '.out'],
            'clean': True}

def task_run():
    yield {
        'name': 't1',
        'actions': ['touch %(targets)s'],
        'targets': ['a.in', 'b.in', 'c.in'],
        'clean': True}

    yield {
        'name': 'build',
        'doc': doc=task_build.creator.__doc__,
        'loader': task_build}
```
The dodo file would be something like:
```python
# dodo.py
from example import task_run
```

**Comment by schettino72** [comment]
When `Task()` is called you are creating the task. Who handles the delayed tasks is the "loader". If you are writing a custom task loader you will have to handle that yourself.

Have you solved your problem?

I am closing this, let me know if you need any change to support this. But adding a `loader` to Task is not the way to handle this...
