### ISSUE TITLE
Unwanted additions to kwargs for python actions

### ISSUE THREAD

**Issue by TomPace101** [pydoit/doit#221]
The example `dodo.py` below illustrates how, in certain cases, additional keyword arguments are added when providing an arguments dictionary to a python action.

The first action writes the arguments dictionary received out to `kwargs.txt`,
and the second action illustrates how this behavior can cause errors.

There are obvious workarounds for the example below. This is merely intended as a minimal example to illustrate the issue.

I'm using python version 3.6.1, and doit version 0.30.3.

```python
def targfunc(a,b,c):
  "The target function for execution in the python action"
  with open('out.txt','w') as fp:
    fp.write(str(a+b*c))
  return

class MyClass:
  @classmethod
  def write_kwargs(cls,**kwargs):
    "This method will show the keyword arguments received"
    with open('kwargs.txt','w') as fp:
      fp.write(str(kwargs)+"\n")
  @classmethod
  def cause_error(cls,**kwargs):
    "This method will cause the error, by passing unexpected arguments to the target function"
    targfunc(**kwargs)


def task_one():
  argsdict={'a':1,'b':2,'c':3}
  return {'actions':[(MyClass.write_kwargs,tuple(),argsdict),(MyClass.cause_error,tuple(),argsdict)],
          'targets':['kwargs.txt','out.txt']}
```

**Comment by schettino72** [comment]
Fixed. thanks. I even had a unit-test to check the wrong behaviour :nauseated_face:
