### ISSUE TITLE
Make --seek-file default behavior

### ISSUE THREAD

**Issue by rpuntaie** [pydoit/doit#222]
If in the current directory there is no dodo.py, seeking in parent folders should be done automatically, unless a specific file is provided with an -f option.

git, e.g., automatically looks into parent folders.

**Comment by vlcinsky** [comment]
btw nice issue number :-)

Using `-k` option is great feature, I use it sometime too (e.g. for syncing deep tree with remote S3 being able to sync from any directory within the tree).

Anyway, to me the idea having `--seek-file` as default seems too dangerous for few reasons:
- explicit is better then implicit: so it seems better to run the `dodo.py` from current directory unless explicitly allowing to use whatever is on higher level.
- having smaller scope (current directory) under control is simpler then larger one (what may include upper directories too)
- `dodo.py` may do sometime really powerful stuff - and doing so by mistake can be a problem
- current behaviour is without default `--seek-file`, changing that may surprise users

Just my 2 cents.

**Comment by schettino72** [comment]
@rpuntaie do you know you can control this through a shell environment variable?

I agree with vlcinsky. `doit` is not `git`... the default should be conservative. 
IMO env variable makes it convenient enough for who wants to change the behaviour.
