### ISSUE TITLE
`doit.get_var()` fails when invoked from the REPL or when using multiple processes on Windows

### ISSUE THREAD

**Issue by madig** [pydoit/doit#231]
I first reported this here: https://github.com/pydoit/doit/issues/164

I now replicated this on the REPL:
```
>>> import doit
>>> doit.get_var('tag', '')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\...\venv\lib\site-packages\doit\doit_cmd.py", line 35, in get_var
    if not _CMDLINE_VARS:
AttributeError: 'NoneType' object has no attribute 'get'
```

Running `doit -n4` in a project directory leads to the same error. It seems `_CMDLINE_VARS` isn't properly passed to/initialized in subprocesses on Windows?

**Comment by madig** [comment]
The following change in `doit_cmd.py` solves the crash but naturally kills the command line parameters:
```Python
def get_var(name, default=None):
    if not _CMDLINE_VARS:
        return default
    return _CMDLINE_VARS.get(name, default)
```

**Comment by schettino72** [comment]
Why you created another issue if #164 already exist and is still open. If same problem, please close this and add info on #164.

**Comment by madig** [comment]
Well I wasn't sure if these have the same root cause as #164 is about delayed task creation? But okay, will close this one. Can be reopened.
