### ISSUE TITLE
show reason task is not up-to-date

### ISSUE THREAD

**Issue by madsflensted** [pydoit/doit#24]
Show the reason why a task is (would be) executed, e.g. "Missing target: x.y.z" or "Dependencey updated: a.b.c". 

This should be implemented as part of `doit info` command.

**Comment by schettino72** [comment]
@madsflensted this is now on master. Can you please test and check as you expected. Use:

$ doit info --status task_name

**Comment by schettino72** [comment]
@felixfontein I was thinking that it would be better to display only the status and reason when the option `--status` is used. The normal output with file_dep, targets would be omitted.  What do you think?

**Comment by felixfontein** [comment]
@schettino72: both is fine for me. I only use `doit info` and `doit info --status` for debugging, and I spend most of the time finding out why exactly something changed, so running `doit info` twice instead of once doesn't really matter.

**Comment by madsflensted** [comment]
@felixfontein sorry for the long feedback cycle, summer vacation...
I just pulled the master and gave it a spin, and the extra information is very helpful in debugging my tasks.
Thanks :+1:

**Comment by felixfontein** [comment]
You're welcome! I already had some debugging sessions (before this feature) where I would have really liked something like that, too.
