### ISSUE TITLE
`--pdb` support to debug error on task execution 

### ISSUE THREAD

**Issue by madig** [pydoit/doit#240]
Support post-mortem debugger for unhadled task execution exceptions.

This must handled separately from exceptions on load time. 
Because doit catches tasks errors and keep running... 

----------------
(original report)

I'm trying to debug a doit pipeline and need to break into pdb in a library I'm using from doit. Unfortunately, doit captures all in- and output, which I have to undo everywhere I'm trying to debug. Would be nice to have the above mentioned parameter that lets me just do `import pdb; pdb.set_trace()` (or `breakpoint()` in the upcoming Python 3.7).

For reference, this is the code I currently use to break into pdb:
```
try:
    code_that_crashes_somewhere_in_your_pipeline
except KeyError:
    import pdb, sys; 
    d = pdb.Pdb(stdin=sys.__stdin__, stdout=sys.__stdout__)
    d.reset(); t = sys.exc_info()[2]; d.interaction(None, t)
```

**Comment by schettino72** [comment]
http://pydoit.org/tools.html?highlight=pdb#set-trace

**Comment by Kwpolska** [comment]
And if you are a fan of `print()` debugging, `doit run -v 2` should cut it for both cases.

**Comment by schettino72** [comment]
@madig  I am aware the search on the site needs some improvement... see #205 
Did you try to search it at all? Which keyword have you used?

**Comment by madig** [comment]
I googled "python doit debug" but must embarrassingly admit that I scrolled over your link. Oops. 

The snippet I use above has the nice property to break into pdb where the exception occurs without me having to know in advance where exactly it occurs. pytest has the `--pdb` switch which will launch a pdb shell at the point of the exception. I think that would be useful to have in doit, too.

**Comment by schettino72** [comment]
>  pytest has the --pdb switch which will launch a pdb shell at the point of the exception

Like this: http://pydoit.org/cmd_run.html#pdb :grin: 

But this only works to debug issues that happen when loading tasks.
Not on task execution... actually I too wished sometimes it would work to debug actual task execution.
