### ISSUE TITLE
doit.get_var(): _CMDLINE_VARS is None unless running from doit utility

### ISSUE THREAD

**Issue by madig** [pydoit/doit#241]
This happens when e.g. pulling in a doit helper library that uses `doit.get_var()` but you're running from e.g. pytest instead of doit. I wrapped the method in a try-except block and just use the default, but is this intentional? Shouldn't `_CMDLINE_VARS` just be an empty dictionary when not run from the command line?

**Comment by schettino72** [comment]
*Explict is better than implicit*

`None` means not initialised. 

I like to keep the distinction and its easy enough to solve from your side. 
Maybe from py.test or whatever you are using you can call the API to manipulate that.

```
import doit
doit.reset_vars()
# and even set values...
doit.set_var('foo', 'bar')
```
