### ISSUE TITLE
Submitting tasks to a grid in parallel / asyncio

### ISSUE THREAD

**Issue by davidbrochart** [pydoit/doit#243]
Say I want to submit a huge amount of long-running tasks to a grid (e.g. using `qsub` on SGE), most of which are independent. I want them to execute in parallel but I don't want to use multiprocessing since it would take a lot of resources only to wait for tasks to finish. I think it would be good to use coroutines in that case, and maybe `asyncio`. A task would just launch a command on the grid and regularly check for the target(s) to be created, but release the control flow and let the chance to other tasks to be launched too.
Is it already possible to do that? If not, would it be feasible to implement it?

**Comment by schettino72** [comment]
Parallel execution using asyncIO currently not possible, but feasible to be implemented. The code handling parallel execution is well abstracted, check `doit/runner.py:MRunner`

Regarding sending tasks to a grid. This has came up a few times. I sincerely have never used such systems and have no much idea about it, but I guess I would be able to hack something around it. 
Once a guy implemented something integration but his solution seems not very straight-forward to me and not easy to use, putting a lot of burden on the user creating the tasks.
