### ISSUE TITLE
Positional arguments example in docs fails.

### ISSUE THREAD

**Issue by ryanfreckleton** [pydoit/doit#252]
When I create a `dodo.py` that contains the following code from the documentation:

~~~python
def task_pos_args():
    def show_params(param1, pos):
        print('param1 is: {0}'.format(param1))
        for index, pos_arg in enumerate(pos):
            print('positional-{0}: {1}'.format(index, pos_arg))
    return {'actions':[(show_params,)],
            'params':[{'name':'param1',
                       'short':'p',
                       'default':'default value'},
                      ],
            'pos_arg': 'pos',
            'verbosity': 2,
            }
~~~

I get the following error:

~~~
ERROR: Task pos_args contains invalid field: 'pos_arg'
~~~

`pos_arg` appears to be what's articulated in the code, but I also couldn't find any specific coverage for this feature in the test suite.

**Comment by schettino72** [comment]
You did not show the command line used. But actually doesnt really matter based in the error message.

Which python version are you using? which version of doit?

I **guess** you have a really old doit version. Or you are running latest doit with python2 (which is not supported). 

How did you install `doit`? I tried to put many checks to ensure people do not mistakenly install doit in the wrong python version...

**Comment by ryanfreckleton** [comment]
Hi,

It seems that it was user error, doit 0.29.0 in my python2 environment doesn't support it, but doit 0.31 naturally does.

Sorry for opening an issue before checking versions, doit is a beautiful tool and one of my favorites to use. Thank you for all your time and effort making such a wonderful project.
