### ISSUE TITLE
Realistic example for home page

### ISSUE THREAD

**Issue by takluyver** [pydoit/doit#253]
I just pointed someone on reddit to http://pydoit.org/ , and I realised that the landing page is a bit... abstract. It has an example task definition, but it's just the structure, not a task that you could actually run, and it doesn't say how to use it.

The intro at http://pydoit.org/tasks.html is better - it's a working example, and it tells you about `dodo.py` and the `doit` command. But it's too simple to show why you'd use doit.

I think doit is a pretty cool tool, and it's a pity that it's not more obvious how and why to use it. With your permission, I'd like to try to come up with a meaningful example to put on the homepage, showcasing some of the main features (such as combining Python tasks with shell commands) and explaining how to use it.

**Comment by vlcinsky** [comment]
@takluyver thanks for sharing the view, that doit is cool tool. Last year we have started refactoring of the docs and partial results are seen here: http://doit-tmp-doc.readthedocs.io/en/latest/index.html 
It got stalled for some time, but I shall find some time to move it forward again.

I hope, new landing page will give better impression for new-commers and help converting more of them in long-term doit users.

**Comment by takluyver** [comment]
Thanks @vlcinsky ! That site is definitely more the sort of landing page I was thinking of. Let me know if there's anything I can help with to unstick the new docs.

**Comment by takluyver** [comment]
So I guess that would be a homepage that people would see before the docs? :-)

It's certainly a more visually attractive landing page. My take is that the target audience for something like doit will understand what it is from an example better than a description. A task runner is inherently a hard thing to describe, because it's so generic.

I like the example on the page @vlcinsky linked to, but I think it's worth trying to show two tasks, one with a shell command and one with Python, with a dependency between them, to illustrate the central features of doit. Maybe instead of creating an archive, extract one and then do something in Python with the extracted data? I know this will make a rather long piece of code, but I think it's worth it.

Also, an unrelated thought on your WIP homepage: 18 of those little feature bubbles looks like too much. They take more than two screen heights on my laptop, so it's a lot of scrolling. Can we condense them down to maybe 6 key ones (2 rows)?

**Comment by takluyver** [comment]
Nice! I think it's a pretty good example - it shows how doit can mix Python functionality and system commands. And I like the side-by-side code block and shell section showing how you'd use it.

I'd still make the example more prominent. At present, I have to scroll down about two full screens in a maximised window on my laptop to see the example - and until I see that, all I've really picked up is that it's something like `make` but using Python. Maybe this is just my perspective, but I'm not interested in a list of advantages until I've got a better idea what the tool is and how I'd use it in practice.

I really like this about [the example docs @vlcinsky showed](http://doit-tmp-doc.readthedocs.io/en/latest/index.html): as soon as I open the tab, I can see an example straight away.

**Comment by schettino72** [comment]
Done http://pydoit.org/
Also updated the sphinx template to something that works better on mobile devices.

Thanks for feedback. very much appreciated :)
And special thanks to @vlcinsky from who i got significant parts of the added text.
