### ISSUE TITLE
Save process return code in CmdAction

### ISSUE THREAD

**Issue by Valitseja** [pydoit/doit#255]
An improvement in CmdAction behaviour would be to save return code of the process, so it is available for the other actions in the task.

e.g. a command returns error code -3 on which the other actions in the task must react.

**Comment by vlcinsky** [comment]
Last sentence of [cmd-action](http://pydoit.org/tasks.html#cmd-action) reads:

> If the process exits with the value 0 it is successful. Any other value means the task failed.

It means, that if process does not succeed (e.g. returns status code -3), the task is considered as failed and no more actions within given task will be run, so the following actions in given task would have no chance to react to the status code.

**Comment by Valitseja** [comment]
@vlcinsky Hmm.. yes that is true. What I am struggling is running a task/sub-task even though the previous task/sub-task failed. E.g. notify user of the failed task which contains some data passed to the previous task. 

Should I save the data to dict before executing the tasks or is there a internal system that I am not aware of? 

NB: I have scanned the document several times and still learning so forgive me my ignorance : )

**Comment by Valitseja** [comment]
Okey, I think I got it, I have to use the teardown and setup entries in the task creation, right?

**Comment by vlcinsky** [comment]
@Valitseja no problem. 

One need I had few times was to have an action tolerating possible failure. In `Makefile` and `systemd` units are such tasks typically marked by "-" prefix. For shell commands there are trick such as:
```$ ls missing-file.txt || true
```
which is always supposed to report success.

I did not resolve the `CmdAction` way of running such command. I would think of extending `CmdAction` or do my custom one which would somehow allow for definition of acceptable result codes or even use some callback to evaluate task result.

Not sure, if this relates to your use case. Teardown might be a place to run some postprocessing (I never tried that).

**Comment by Valitseja** [comment]
@vlcinsky I think the callback system to evaluate the result sounds quite good. The 'teardown' worked for me, but it is more work as I need to parse the result output compared to check the return code of the command.

**Comment by schettino72** [comment]
I agree @vlcinsky . I custom "CmdAction" class would be the best approach.

`teardown` was created to handle several tasks sharing a "teardown".

ps. please use the mail list. github only for issues.
