### ISSUE TITLE
YAML as a simple task creator?

### ISSUE THREAD

**Issue by Dracks** [pydoit/doit#259]
Hello, 

Today I discover doit, and working with it, (a basical configuration) I was thinking that maybe it can be saved on a yaml file, because my configuration is really simple. 

My file is [this](https://github.com/Dracks/finances/blob/develop/dodo.py)

In a future, I will put some logic for "uptodate" and other things, maybe some check step. Did you think about that?

**Comment by schettino72** [comment]
you can easily load any time of configuration from `dodo.py`
