### ISSUE TITLE
tutorial is absent from the source file (0.31.1)

### ISSUE THREAD

**Issue by jose-matos** [pydoit/doit#264]
While packaging 0.31.1 for Fedora I noticed that the tutorial is absent from the documentation in the source tar.gz.

Was that done on purpose or was it a mistake? If the later could you add it to the source tar.gz for the next stable release?

**Comment by schettino72** [comment]
Tutorial was written **after** last release. It will be included in next release.

Note: I also changed the sphinx theme... and planning to theme again before next release (use my own https://github.com/schettino72/sphinx_press_theme). 
So I would not spend time for now dealing with packaging changes (if any) related to changes in docs.

And thanks for packaging doit :smiley:
