### ISSUE TITLE
Example for running tasks from code

### ISSUE THREAD

**Issue by koliyo** [pydoit/doit#268]
I would like to start doit tasks from inside python code. Not using the command line. Is there an example showing this?

**Comment by cha-ku** [comment]
Do you want to call doit from inside python files? Using doit as a library? If yes, then I am not sure this can be done.

**Comment by koliyo** [comment]
Ok, thanks for response! I guess it is possible to use calls to `subprocess` etc. I will think about if I need to adjust my pipeline design a bit.
