### ISSUE TITLE
Problems running tests

### ISSUE THREAD

**Issue by dvzrv** [pydoit/doit#269]
I'm currently moving doit to Arch Linux' [community] repository.
After build and before packaging I would like to run the tests, but they currently fail:
```
============================= test session starts ==============================
platform linux -- Python 3.7.0, pytest-3.8.0, py-1.6.0, pluggy-0.7.1
rootdir: /build/python-doit/src/python-doit-0.31.1, inifile:
collected 597 items / 1 errors

==================================== ERRORS ====================================
__________________ ERROR collecting tests/test_dependency.py ___________________
tests/test_dependency.py:72: in <module>
    pytest.fixture(params=[JsonDB, DbmDB, SqliteDB])(pdep_manager)
/usr/lib/python3.7/site-packages/_pytest/fixtures.py:1003: in __call__
    "fixture is being applied more than once to the same function"
E   ValueError: fixture is being applied more than once to the same function
=============================== warnings summary ===============================
<unknown>:90: DeprecationWarning: invalid escape sequence \]

<unknown>:97: DeprecationWarning: invalid escape sequence \]

-- Docs: https://docs.pytest.org/en/latest/warnings.html
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
===================== 2 warnings, 1 error in 1.22 seconds ======================
```

With Arch we're on python 3.7.0, setuptools 40.2.0, cloudpickle 0.5.3, pytest 3.7.4, coverage 4.5.1, pyinotify 0.9.6, flake8 3.5.0.
In any case the above error seems to be an issue with how the tests are being executed. Maybe someone from the project can shine some light on it?
Any help would be greatly appreciated!

**Comment by schettino72** [comment]
You mentions pytest 3.7.4 but logs says pytest 3.8...

Which doit version?
A few days ago I fixed (on MASTER) a problem caused by newer version of py.test (https://github.com/pydoit/doit/commit/50f0c7eaa8084e3a54c88bfec02e477e419f4c12).

So yeah released version, expected to have failures.

**Comment by dvzrv** [comment]
Oh, that's correct. Checked my local version when writing the issue (which was still 3.7.4). However, the packages are build in a pristine nspawn container with latest dependencies (hence there it was 3.8.0 already).
Okay, great to see that it's most likely already fixed! Will include it in the next release then :)
