### ISSUE TITLE
auto command in conjunction with task arguments

### ISSUE THREAD

**Issue by gergelyk** [pydoit/doit#27]
'auto' command interpretes task arguments as names of tasks. As an effect execution of the command failes. The same syntax works fine with 'run' command. Example:

    # this works fine:
    $ doit run mytask -p arg1 -q arg2

    # this failes:
    $ doit auto mytask -p arg1 -q arg2

**Comment by schettino72** [comment]
Thanks for the report, please include a sample `dodo.py` to reproduce the problem.

**Comment by gergelyk** [comment]
Here you go:
http://pastebin.com/k9tyyEMp

**Comment by schettino72** [comment]
actually fix on https://github.com/pydoit/doit/commit/83af7946f51fa5536c9875d79eb39defd8879bff
but i put wrong issue number on original commit...

please verify

**Comment by gergelyk** [comment]
Works fine now. I tested with the same sample code. Thanks for your work!

**Comment by schettino72** [comment]
You're welcome. Please consider supporting doit development through [gratipay](https://gratipay.com/schettino72/).
