### ISSUE TITLE
Set task options from doit.cfg

### ISSUE THREAD

**Issue by rbdixon** [pydoit/doit#283]
Per [thread](https://groups.google.com/forum/#!topic/python-doit/4PnYOeNO5SI): I'd like to set task parameters from doit.cfg as well. It seems possible since the `doit help <task>` section lists the config name to use but config stanzas based on the task name are ignored:

```
[<taskname>]
foo = bar
```

@schettino72 said that this is not currently possible.

**Comment by smarie** [comment]
Thanks @rbdixon , I added a review to your PR

That feature is very important for our use cases: indeed we need users to provide secret API keys. Of course we could do it in custom code, but it would make a lot of sense to have it in `doit`.

**Comment by arichiardi** [comment]
Hi there, sorry if I am hijacking this, but is this feature only working for `python_action` - not for `cmd_action`?

I had to the following but maybe I am doing something wrong:

```python
 def image_action(docker_registry, docker_repository):
        image_tag = docker_image_qualified_name(docker_registry, docker_repository, namespace_tag)
        cmd = ["docker", "build", "--tag", image_tag, Path(".")]
        returncode = subprocess.call(cmd, shell=False)
        if returncode != 0:
            return doit.exceptions.TaskFailed(
                "Command failed: '%s' returned %s" % (cmd, returncode))

    return {
        "file_dep": [REACTOR_JAR_PATH, dockerfile_path],
        "actions": [image_action],
        "uptodate": [False],
        "params": [{"name": "docker_registry",
                    "long": "docker-registry",
                    "type": str,
                    "default": None,
                    "help": "The url to the docker registry."},
                   {"name": "docker_repository",
                    "long": "docker-repository",
                    "type": str,
                    "default": None,
                    "help": "The string representing the docker repository."}],
```

**Comment by rbdixon** [comment]
Yes, I'd open a new issue or submit a patch if possible. A minimal test case is always useful. What you have above is probably close. Just prune out all of the details and try to make it as simple as possible. Mention me in the new issue and I can take a look in January.
