### ISSUE TITLE
"clean" cannot be given as a task_dep

### ISSUE THREAD

**Issue by assarbad** [pydoit/doit#308]
It seems odd that the list for `task_dep` cannot accept `"clean"` ... also, even if it could (which I think would be the natural thing to do), it would be unclear how to switch the modes of that task (`cleanall` etc).

The idea was to have a `task_rebuild` like so:

```
def task_rebuild():
    return {
        "actions": [],
        "task_dep": ["clean", "all"],
        }
```

**Comment by moltob** [comment]
Please note that in doit `clean` is not a task but a command that can act on your tasks, just like `run` or `forget`. So you can't add a task dependency.

**Comment by assarbad** [comment]
Well, so how do I achieve what I want?
