### ISSUE TITLE
dodo.py requirements file

### ISSUE THREAD

**Issue by smarie** [pydoit/doit#315]
I could not find in the documentation any reference on how to specify a requirements file for the `dodo.py` script itself. For example if in some module-level script in my dodo.py script need a specific package: how should I do ? Currently the workaround is to put all the code requiring dedicated packages in a task, so that this task can require another `install_requirements` task. It is a bit tideous...

It would probably make sense to support a simpler way to automatically check/install "global" (=module-wide) dependencies of a `dodo.py`script. 

I see two things that could be done:

 * a `dodo_requires.txt` file 
 * a `dodo_requires.py` script, that could contain any number of doit tasks and would be executed prior to main `dodo.py` execution

Does it make sense ? 

I would personally think that **only the first option (txt) is enough**, because the second (script) could naturally be done by rearchitecturing the `dodo.py` file (basically, putting everything that requires specific packages in another file and only creating the corresponding tasks if it can be imported).

**Comment by moltob** [comment]
Since requirements files are for applications and your application is doit, why don't you just use the same requirements file used to install doit? If tasks need other packages you should probably put those dependencies into the same requirements file. Makes sense?

**Comment by schettino72** [comment]
Thanks Mike. Yes, out of scope.

**Comment by smarie** [comment]
Thanks @moltob ! however I am not quite satisfied with this answer, sorry :)

The issue is the famous "chicken & egg" bootstrap problem, or reformulated otherwise, "what is the main build tool of my project" question. If the main build tool of a project is `doit`, then you should not expect users to install anything else than `doit` in order to build it. Just like `make`.

I'll try to illustrate this with an example: if I create a project (an application) using `doit`, I would expect to write the following `README` file:

```
Hi, welcome to my project ! 
To build it you just need to `pip install doit` and then execute `doit` in the folder. 
That's all !
```

However if `dodo.py` has requirements, I would need to add them to that readme. That's the beginning of something that is outside `doit`. So that's the beginning of "`doit` is not the main entry point to build this project".

Is this somehow understandable ?

**Comment by moltob** [comment]
```
Hi, welcome to my project ! 
To build it you just need to `pip install -r <folder>/requirements.txt` and then execute `doit` in the folder. 
That's all !
```

**Comment by smarie** [comment]
I see. I guess I would keep the name `dodo_requires.txt` then, because usually `requirements.txt` are for the application (for example if it is a python package) and not for the build system itself, no ? Or maybe I mix the two concepts.

Thanks anyway !

**Comment by schettino72** [comment]
I actually never used it but someone contributed this:

https://github.com/pydoit/doit/wiki/Standalone-script-(install-doit-on-the-fly)
