### ISSUE TITLE
Merge all `.doit.xxx` files in a single `.doit/` folder

### ISSUE THREAD

**Issue by smarie** [pydoit/doit#317]
I noticed that `doit` creates several files located at the project root.

The usual practice for projects doing this (e.g. pytest, pycharm, I think tox too, etc.) is to store their files in a dedicated folder.

Could we consider creating a `.doit` folder and putting all doit-created files in it ?

**Comment by schettino72** [comment]
This depends on dbm module being used. For me (on linux) only one file is created.
There is already #223 that mention some naming problems.

I agree that putting all files in a folder (only for DBM backends that create more then one file).

I am closing this and adding a note on #223

**Comment by smarie** [comment]
Great!

**Comment by vipranarayan14** [comment]
I was able to achieve this by creating a folder named '.doit' inside the project root folder and configuring the dep_file path as:

```py
# dodo.py
DOIT_CONFIG = {
    "dep_file": ".doit/.doit.db",
}
```
