### ISSUE TITLE
More pythonic first-class citizens such as `CmdOption` and others 

### ISSUE THREAD

**Issue by smarie** [pydoit/doit#318]
(edited for clarity following conversation below, thanks @moltob )

It would be great to support usage of `CmdOption` instances in `'params'`, justlike `Task` can be used instead of a dict.

In addition, currently `CmdOption` currently has a 'generic' constructor that does not contain argument names in the signature:

```python
class CmdOption(object):
    def __init__(self, opt_dict):
        # options must contain 'name' and 'default' value
        opt_dict = opt_dict.copy()
        for field in ('name', 'default',):
            if field not in opt_dict:
                msg = "CmdOption dict %r missing required property '%s'"
                raise CmdParseError(msg % (opt_dict, field))

        self.name = opt_dict.pop('name')
        self.section = opt_dict.pop('section', '')
        self.type = opt_dict.pop('type', str)
        self.set_default(opt_dict.pop('default'))
        self.short = opt_dict.pop('short', '')
        self.long = opt_dict.pop('long', '')
        self.inverse = opt_dict.pop('inverse', '')
        self.choices = dict(opt_dict.pop('choices', []))
        self.help = opt_dict.pop('help', '')
        self.env_var = opt_dict.pop('env_var', None)
```

It is not very elegant and straightforward, and it is not introspectable using python default mechanisms. So, users can not get autocompletion and documentation easily from their IDE.

The following reformulation would make it much easier for users to call, because the IDE would provide autocompletion:

```python
class CmdOption(object):
    def __init__(self, 
                 name,         # type: str
                 default,      # type: Any
                 section='',   # type: str
                 type=str,     # type: Type[Any]
                 short='',     # type: str
                 long='',      # type: str
                 inverse='',   # type: str
                 choices=(),   # type: Iterable[Any]
                 help='',      # type: str
                 env_var=None  # type: Any
                 ):
        """
        blabla
        """

        self.name = name
        self.set_default(default)
        self.section = section
        self.type = type
        self.short = short
        self.long = long
        self.inverse = inverse
        self.choices = choices
        self.help = help
        self.env_var = env_var
```

And calling code would just need to do:

```
try:
    cmd_opts = CmdOption(**opt_dict)
except TypeError as e:
    raise CmdParseError("Error creating CmdOption from dict %r: '%s'" % (opt_dict, e))`
```

Note that there may be additional classes in the data model where the same comment applies.

As always I can work on a PR if you wish - that should not be too difficult.

**Comment by smarie** [comment]
Note that this is already done for the `Task` class.

By the way, I see that you reimplemented your own class definition/fields validation system. Maybe using `attrs` or `autoclass` , with or without `valid8`, could help one day... but no hurry since you've done it already ;)

**Comment by moltob** [comment]
@smarie Please consider that making statements like above, pointing out _non-pythonic_ code and pep8 inconsistencies might not be the optimal way to introduce yourself to an open-source project.

Also, please realize that this project is around for many years (since 2008 if I read correctly), so some historical baggage like that should be acceptable. Furthermore, refactoring like this may break things for users in the wild, even though the project has a decent test coverage.

As usual @schettino72 makes the call, but personally, I'd rather not run the risk of breaking my production toolchain, that heavily relies on doit, because a developer did not like the code style.

Do you see the reasoning?

**Comment by smarie** [comment]
@moltob I realize from your comment that there was some misunderstanding, probably due to my bad writing. This is absolutely not a style-related remark. I care as little as you do about pep8 :). Actually you will notice that I made effort in PR #321 to try to adapt to the style in place - even if that's not my style.

No, this issue was actually about a user-related feature. The intent is for users to be able to use the following syntax to define parameters in tasks:

```python
{'params': [CmdOption(name='myparam', short='p', long='myparam', default='whatever')]}
```

(note the `CmdOption` usage). This would not be a replacement for the existing syntax, but an alternative, completely consistent with what is already proposed for tasks (you can use a dictionary OR a `Task` instance).

I'll try to edit the title to reflect this.

Now about the rest of your comment, well I cannot agree with it because continuous improvement is part of projects normal lifecycle. That's the role of continous integration and tests to ensure that a codebase is retrocompatible. And if by chance something breaks that is actually good news: that means that the tests were not good enough, and therefore there is an opportunity to improve overall quality. 

Freezing an entire codebase for years by fear of breaking something was maybe the norm in the 1990s but it is not true anymore, even in the industry (I am from this world too :) ). Of course for all production stuff we freeze the versions of our dependencies, but note the difference: we freeze the dependency version in our projects, not the sources in the git repository of the dependency.

Sorry again for the misundersanding - I'll fix the title now

**Comment by schettino72** [comment]
``doit`` was designed on the idea the most common stuff is done without the need to import custom ``doit``  classes. Same principle was used for command line argument definitions. So doit uses plain dict as interface in many places...

So the initializer takes a simple dictionary. Of course there are some trade-offs... as you pointed out.
