### ISSUE TITLE
More intuitive internal structure with sub packages

### ISSUE THREAD

**Issue by smarie** [pydoit/doit#319]
Currently files are organized in a "flat" mode:

![image](https://user-images.githubusercontent.com/3236794/61949276-93c56880-afaa-11e9-8ed6-aca8e0ae4d9f.png)

It makes it quite difficult for newcomers to reverse-guess the architecture from package organization. I'm sure that a few separate folders could be identified to better structure this

Any ideas?

**Comment by schettino72** [comment]
I guess the best way to better understand the module structure of a project is a graph of import dependencies. Actually doit owns tutorial is a project on how to create those. I should probably include that generated graph for doit itself on docs...

I think that given doit size, a flat module structure fits better.

**Comment by smarie** [comment]
I disagree, but that's your call ;)
