### ISSUE TITLE
Being able to pass a task parameter from the CLI without running specifically that task

### ISSUE THREAD

**Issue by smarie** [pydoit/doit#324]
Consider the following `dodo.py` file:

```python
DOIT_CONFIG = {'default_tasks': ['mytask']}

def task_mytask():
    return {
            'params': [{
                'name': 'myparam',
                'short': 'p',
                'long': 'myparam',
                'default': 'param_default',
            }],
            'actions': ["echo myparam is %(myparam)s"],
            'verbosity': 2,
        }
```

Currently the following works:

```
>>> doit mytask --myparam hello
.  mytask
myparam is hello

>>> doit
.  mytask
myparam is param_default
```

But the following does not:

```
>>> doit --myparam hello
ERROR: Error parsing Command: option --myparam not recognized (parsing options: ['--myparam', 'hello'])
```

It would be quite intuitive that the above works too. Indeed it is a bit strange to have to introduce a global `getargs` parameter, just to support this use case. In particular it would be annoying because one would need to reconciliate both.

Related tickets:

 * #283 is about ability to define task parameters in the `doit.cfg` file.
 * #311 is about the ability to define task parameters in a decorator rather than the dictionary AND the ability for parameters passed to a task group to be passed to subtasks automatically.

**Comment by arichiardi** [comment]
Isn't this somehow solved by `doit.get_var`?

I am asking because I am running into this as well and wondering if I am doing it right.

**Comment by schettino72** [comment]
@smarie the problem with this approach is that it would make it impossible to detect when a wrong a parameter is passed for the main command.

`doit` is strict and tries hard to not let pass errors pass silently...
It goes with python philosophy. Explicit is better then implicit. 
A task parameter must be specified for the task!

It is also easy to subclass and replace the `run` sub-command adding you own parameters.

**Comment by smarie** [comment]
Thanks for answering @schettino72 

> the problem with this approach is that it would make it impossible to detect when a wrong a parameter is passed for the main command.

I dont' understand why? Since `doit` is able to collect the full list of tasks, it is able to retrieve their parameters definition, no ?

> A task parameter must be specified for the task!

Yes - and that's what this ticket is actually about: the issue that I would like fixed is that users cannot easily pass a parameter for a task from commandline. If you have a default lifecycle of 10 tasks, and one of them has a parameter, you cannot call the default lifecycle with that parameter in commandline, which is quite sad.

Maybe using a task name prefix in the parameter would fix your concerns ? That way it is easy for `doit` to find the task associated with the parameter. Like this:

```
>>> doit --mytask:myparam hello
```

That prefix would be optional when doit is called just for a single task

```
>>> doit mytask --myparam hello
```

What do you think?

**Comment by schettino72** [comment]
You are still giving an example of a correct input from user. What should be the error message for this:

`doit --invalid-parameter-that-doesnt-exist`

Is it doit invalid parameter? command `run` parameter? a task parameter?
And keep in mind that sub-commands are loaded dynamically, and tasks are loaded **after** the sub-command is processed.

> If you have a default lifecycle of 10 tasks, and one of them has a parameter, you cannot call the default lifecycle with that parameter in commandline, which is quite sad.

Can you show full example of waht you are typing?

----

Compare your suggestion:
```
>>> doit --mytask:myparam hello
```

Supposing you can create a task group for default tasks as `d`. you can write:
```
>>> doit d mytask --myparam hello
```

**Comment by smarie** [comment]
Hi I'm back after a while, apologies for this.

So my point is: if you consider the following `dodo.py` file with a default lifecycle of two tasks, the second having a shared parameter:

```python
DOIT_CONFIG = {'default_tasks': ['a', 'mytask']}

def task_a():
    def python_hello(targets):
        with open(targets[0], "a") as output:
            output.write("Python says Hello World!!!\n")

    return {
        'actions': [python_hello],
        'targets': ["a.txt"],
    }

def task_mytask():
    for i in range(2):
        yield {
            'name': "mytask-%s" % i,
            'params': [{
                'name': 'myparam',
                'short': 'p',
                'long': 'myparam',
                'default': 'param_default',
            }],
            'actions': ["echo %s myparam is %%(myparam)s" % i],
            'verbosity': 2,
            }

```

Currently the following works:

```
>>> doit mytask:mytask-1 --myparam hello
.  mytask:mytask-1
1 myparam is hello

>>> doit
.  a
.  mytask:mytask-0
0 myparam is param_default
.  mytask:mytask-1
1 myparam is param_default
```

What I would like is :

```
>>> doit --myparam hello
```

but I guess that it is reasonable to have to enter some prefix so that the parameter is validated:

```
>>> doit --mytask:myparam hello
```

That way, invalid parameter names could easily be checked :

```
>>>  doit --invalid_param hello
Error: invalid global parameter 'invalid_param'. If this parameter is related to a task, please prefix it with the task name as in `--<task_name>:invalid_param`

>>> doit --mytask:invalid_param hello
Error: invalid parameter 'invalid_param' for task (group) 'mytask'.

>>> doit --invalid_task:invalid_param hello
Error: invalid task prefix 'invalid_task' used for parameter '--invalid_task:invalid_param'.
```

Note that maybe the last case can not be easily checked upfront, but can be done after task collection (before task run).

Does it make sense ? Maybe I overcomplexified this example because there is a subtask generator but you get the main idea. If there is an elegant alternative I would be glad to know it ; and if so the example could be added in the documentation to benefit most users.

Thanks again for your time!
