### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by inakimalerba** [pydoit/doit#332]
Dear Developers,

I'm one of the uploaders of doit in Debian. The latest release was 0.31.1 a long time ago.

Is there any blocker to make a new one? 

Thanks.

**Comment by moltob** [comment]
I'll second the request and would greatly appreciate a new release.

**Comment by schettino72** [comment]
Sorry,  I just want to merge pending PRs before making a release...

**Comment by boileaum** [comment]
I also look forward a new release. Especially because the latest release is outdated compared to the online documentation. Congratulations for the work, by the way!

**Comment by schettino72** [comment]
done. sorry for delay
