### ISSUE TITLE
-bash: doit: command not found

### ISSUE THREAD

**Issue by cx4** [pydoit/doit#336]
my OS is centos7
I installed python3 and pip3
i use pip3 install doit
but in shell command use doit list 
![Mzfk0s.png](https://s2.ax1x.com/2019/11/26/Mzfk0s.png)

**Comment by madig** [comment]
The `doit` script is presumably not in your PATH environment variable. You will have to look up where pip installs scripts. Try using `python3 -m pip` instead of `pip`.

**Comment by schettino72** [comment]
@cx4 not a doit issue. You might look for help in a python forum.
