### ISSUE TITLE
setup.py misses test dependencies?

### ISSUE THREAD

**Issue by hartwork** [pydoit/doit#345]
Hi!

is there a particular reason why `setup.py` does not declare test dependencies?
I found at least:
- `cloudpickle`
- `doit-py`
- `pyflakes`
- ~`pyinotify`~
- `pytest`

Would you welcome a pull request to add them?

**Comment by schettino72** [comment]
Please check https://github.com/pydoit/doit#development-setup

Or you mean there is a more modern way to that?

**Comment by hartwork** [comment]
I have pushed a demo as pull request #345 now for 
- the missing [`tests_require`](https://setuptools.readthedocs.io/en/latest/setuptools.html#options) that I created the ticket for, mainly
- a demo how both requirement files could be resolved (if you want to).
