### ISSUE TITLE
installation failure: fatal error: too many errors emitted, 193 warnings and 20 errors generated.

### ISSUE THREAD

**Issue by eugenetaranov** [pydoit/doit#351]
**Describe the bug**

Doit installation fails:

`Collecting doit
  Using cached https://files.pythonhosted.org/packages/1f/89/b5e1dd4854b47c4f9e5250899c04e0cd0c9082c30ef619c0413ace20cf7a/doit-0.32.0.tar.gz
Requirement already satisfied: cloudpickle in /Users/eugene/.pyenv/versions/3.7.4/envs/alice/lib/python3.7/site-packages (from doit) (1.2.2)
Collecting macfsevents (from doit)
  Using cached https://files.pythonhosted.org/packages/28/2e/1ff399cfd2a6a8ebb65152203c920643c2169aa507b2e96559d19baeb7c3/MacFSEvents-0.8.1.tar.gz
Installing collected packages: macfsevents, doit
  Running setup.py install for macfsevents: started
    Running setup.py install for macfsevents: finished with status 'error'
    Complete output from command /Users/eugene/.pyenv/versions/3.7.4/envs/alice/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/mn/pxsk0kzx22jg33pwymz8pytc0000gn/T/pip-install-1klhofzk/macfsevents/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/mn/pxsk0kzx22jg33pwymz8pytc0000gn/T/pip-record-tzjrd1hm/install-record.txt --single-version-externally-managed --compile --install-headers /Users/eugene/.pyenv/versions/3.7.4/envs/alice/include/site/python3.7/macfsevents:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.14-x86_64-3.7
    copying fsevents.py -> build/lib.macosx-10.14-x86_64-3.7
    running build_ext
    building '_fsevents' extension
    creating build/temp.macosx-10.14-x86_64-3.7
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -I/Users/eugene/.pyenv/versions/3.7.4/envs/alice/include -I/Users/eugene/.pyenv/versions/3.7.4/include/python3.7m -c _fsevents.c -o build/temp.macosx-10.14-x86_64-3.7/_fsevents.o
    In file included from _fsevents.c:1:
    In file included from /Users/eugene/.pyenv/versions/3.7.4/include/python3.7m/Python.h:25:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/stdio.h:64:
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/_stdio.h:93:16: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
            unsigned char   *_base;`

**Environment**
1. OS: macOS Catalina, 10.15.2
2. python version: 3.7.4
3. doit version: 0.32.0

Please see detailed log attached.
[out.log](https://github.com/pydoit/doit/files/4153396/out.log)

**Comment by hartwork** [comment]
Hi Eugene,

based on the log you provided I believe the issue seems to be with macfsevents, not doit itself.

If macfsevents 0.8.1 does not work have
- tried a different version (`0.1`, `0.2`, `0.2.1`, `0.2.2`, `0.2.3`, `0.2.4`, `0.2.5`, `0.2.6`, `0.2.7`, `0.2.8`, `0.3`, `0.4`, `0.5`, `0.6`, `0.7`)?
- checked the macfsevents Git repositories for related fixes?
- discussed the issue with macfsevents upstream?

Best, Sebastian
