### ISSUE TITLE
tests missing in pypi sdist

### ISSUE THREAD

**Issue by dvzrv** [pydoit/doit#371]
**Describe the bug**

Hi! When trying to package 0.33.0 for Arch Linux I realized that all tests are now missing from the pypi sdist tarball.
Can you please add them back? Running tests against the environment is very important in a system packaging context.
 
**Environment**
1. OS: Arch Linux
2. python version: 3.8.5
3. doit version: 0.33.0

**Comment by jose-matos** [comment]
I noticed the same updating the package for Fedora. :-)
Not only tests but also the docs and other files like the shell completions.

**Comment by schettino72** [comment]
Released 0.33.1.
Thanks for report and for packaging doit
