### ISSUE TITLE
Doit does not store task.values when an uptodate callback returns True

### ISSUE THREAD

**Issue by agustinhenze** [pydoit/doit#39]
Hello @schettino72, I was trying to execute an expensive and slow task just once without using run_once because the task could be ready before the existence of doit in our project. The problem is that checking if it is already done is slow too, so I would like to check it once.

Then I tried to implement my own uptodate callback trying to detect if my_expensive_task_is_done method was already executed before but doit does not store new task.values if uptodate returns True, so I am running in circles here... I know, use a file as target and write it only if the task is done (is actually what I did) but it isn't the best solution. I would like to use doit's cache I think it would be more elegant.

**Comment by schettino72** [comment]
Hi Agustin. This is more suitable to the email group list. Please post there and include the code you got so far or a minimum example...

If a task is up-to-date it means wont be execute hence it should not have any values to save. 
I need to think about it looking at an example :) #28 might help you somehow!
