### ISSUE TITLE
Creating commands as described in the docs does not work

### ISSUE THREAD

**Issue by mlell** [pydoit/doit#414]
I tried to implement the directions shown in the docs on how to create a new command for doit. 

The [docs say](https://pydoit.org/extending.html#command-customization):

> To create a new command, subclass doit.cmd_base.
> Command set some class variables and implement the execute method.

Below is my example `dodo.py` file. I copied it verbatim from the docs:

```py
from doit.cmd_base import Command

class Init(Command):
    doc_purpose = 'create a project scaffolding'
    doc_usage = ''
    doc_description = """This is a multiline command description.
It will be displayed on `doit help init`"""

    def execute(self, opt_values, pos_args):
        print("TODO: create some files for my project")
```

After saving, the file, I executed `doit Init`. 

**Expected behaviour**: Output `TODO: create some files for my project` is printed

**Actual behaviour**: Output `ERROR: Invalid parameter: "Init". Must be a command, task, or a target.`

**Environment**
1. OS: Debian
2. python version: 3.9.2
3. doit version: 0.33.1

**Comment by schettino72** [comment]
Keep reading the docs...  you need to register the command as a plugin...

**Comment by mlell** [comment]
I see.
