### ISSUE TITLE
param keeps false when default  value is False and enable inverse

### ISSUE THREAD

**Issue by bingozhu0197** [pydoit/doit#418]
PLEASE DO NOT USE ISSUE TRACKER TO ASK QUESTIONS: see [contributing](https://github.com/pydoit/doit/blob/master/CONTRIBUTING.md)

**Describe the bug**

def task_with_flag():
    def _task(flag):
        print("Flag {0}".format("On" if flag else "Off"))

    return {
        'params': [{
            'name': 'flag',
            'long': 'flagon',
            'short': 'f',
            'type': bool,
            'default': False,
            'inverse': 'flagoff'}],
        'actions': [(_task, )],
        'verbosity': 2
        }

$ doit with_flag --flagoff
.  with_flag
Flag Off

**Environment**
1. OS: x86_64 GNU/Linux
2. python version: Python 3.8.8
3. doit version: 0.33.1

**Comment by schettino72** [comment]
Looks like the expected output to me.
