### ISSUE TITLE
Commands don't work when DB file option is specified?

### ISSUE THREAD

**Issue by jglogan** [pydoit/doit#422]
`dodo.py`:
```
def task_hello():
    return {
        'doc': 'Print something.',
        'actions': [ 'echo Hello, world!' ]
    }
```

What I see:
```
% doit -f dodo.py list
hello   Print something.
% doit --db-file ${PWD}/doit-test.db -f dodo.py list
ERROR: Invalid parameter: "list". Must be a command, task, or a target.
Type "doit help" to see available commands.
Type "doit list" to see available tasks.
```

Is this expected behavior?

**Environment**
1. OS: MacOS 12.3.1
2. python version: 3.9.9
3. doit version: 0.34.2

**Comment by schettino72** [comment]
Only *task-loader* options can be specified before a sub-command (i.e. `list`).
Moving the option after the `list` should work.

```
doit  -f dodo.py list --db-file ${PWD}/doit-test.db
```

Sorry, documentation on this really needs some improvements...

**Comment by jglogan** [comment]
Interesting...so it would seem that if I'm building a wrapper script to handle this, it somehow needs to know the difference between a subcommand and a task in order to get the args correct?

For example, this very simplistic wrapper:

```
#! /bin/bash -ex

if [ $# -ge 1 ] ; then
    doit -f dodo.py "${1}" "${@:2}"
else
    doit -f dodo.py --db-file "${PWD}/.doit.db" "$@"
fi
```

**Comment by jglogan** [comment]
It would seem that if I want to write a wrapper script, then I'd need to do something along the lands of this to handle subcommands separately from tasks?

```
#! /bin/bash -e

case "$1" in
    auto | clean | dumpdb | forget | ignore | info | list | reset-dep | run | strace | tabcompletion | tasks)
        doit -f dodo.py "${1}" --db-file "${PWD}/.doit.db" "${@:2}"
        ;;
    help)
        doit "$@"
        ;;
    *)
        doit -f dodo.py --db-file "${PWD}/.doit.db" "$@"
        ;;
esac
```

**Comment by schettino72** [comment]
Note that parsing CLI options is strict as not accepting unrecognized options.
Configurations are more flexible in this aspect. You can specify an option to all commands, and those are options are ignored if they do not apply.

dodo.py
```
DOIT_CONFIG = {"dep_file": "doit-test.db"}
```
