### ISSUE TITLE
No auto command on version 0.36.0

### ISSUE THREAD

**Issue by gkutiel** [pydoit/doit#425]
PLEASE DO NOT USE ISSUE TRACKER TO ASK QUESTIONS: see [contributing](https://github.com/pydoit/doit/blob/master/CONTRIBUTING.md)

**Describe the bug**

It seems that the auto command was removed in version 0.36.0
```
~ doit auto                                             
ERROR: Invalid parameter: "auto". Must be a command, task, or a target.
Type "doit help" to see available commands.
Type "doit list" to see available tasks.
```

**Environment**
1. OS: macOs
2. python version: 3.9
3. doit version: 0.36.0

**Comment by schettino72** [comment]
thanks for letting me know. /s
