### ISSUE TITLE
Building version `>= 0.36.0` conda package  for windows with python 3.11

### ISSUE THREAD

**Issue by hovavalon** [pydoit/doit#457]
Hello,
I am working on the development of features for the `scipy` library on a windows 11 machine and a `conda` environment.
I have recently tried to upgrade my python version from `3.10` to `3.11`, and now I can't install `doit>=0.36.0`.

```
>conda install -d "doit>=0.36.0"
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - doit[version='>=0.36.0']

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

Am I missing anything here?
Should I try to install the package in another way?
If there is anything I can do in order to help solve this issue I would be happy to.

<a href="https://dashboard.polar.sh/pydoit/doit/issues/457">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://dashboard.polar.sh/api/github/pydoit/doit/issues/457/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://dashboard.polar.sh/api/github/pydoit/doit/issues/457/pledge.svg">
</picture>
</a>

**Comment by schettino72** [comment]
doit 0.36 is available on conda-forge

https://anaconda.org/conda-forge/doit
