### ISSUE TITLE
"sqlite3.OperationalError: database is locked" in parallel execution

### ISSUE THREAD

**Issue by JohannesBuchner** [pydoit/doit#65]
Hi,

Sometimes when executing doit with parallel execution (e.g. -n 10), I get the following error:

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
OperationalError: database is locked
Error in sys.exitfunc:
sqlite3.OperationalError: database is locked
```

This is with python-sqlite2 version 2.3.5.

I am not sure how to debug this, because it seems to appear randomly. It does however effect running tasks, I think it closes their stdin/out or sends them a signal.

**Comment by schettino72** [comment]
full traceback? Your tasks use sqlite? looks like a problem on your own code... your tasks must be able to run in parallel.

The error is `sqlite3.OperationalError` but you mention sqlite2!

Please re-open if really a doit issue.

**Comment by JohannesBuchner** [comment]
Oh so doit actually does not use sqlite! 

Then as you say, there is a race condition in the program I run, probably reading its database at launch. That makes more sense, thank you!. 

PS: The sqlite3 connection package is called like that in [CentOS](http://rpm.pbone.net/index.php3/stat/4/idpl/23763368/dir/centos_6/com/python-sqlite2-2.6.0-17.1.x86_64.rpm.html), don't know why.

**Comment by schettino72** [comment]
`doit` uses sqlite only if you specify `--backend=sqlite3` on command line. I thought sqlite3 would manage the concurrency for you, I have no idea why you would get this error.
