### ISSUE TITLE
docs: add a section to advertise other projects based on doit

### ISSUE THREAD

**Issue by JohannesBuchner** [pydoit/doit#68]
Hi, this is not really a bug report.

I created a Reporter that makes html progress report pages, live.
https://github.com/JohannesBuchner/doithtml
Demo included.
Just wanted to let you know.

Cheers,
             Johannes

**Comment by schettino72** [comment]
Cool, I glad to see work being done on this. 
I plan to build something like this for many years but never got into it :(

Thanks for notifying me about this. I will change this bug to make sure I include a link to it somewhere in the official docs.

**Comment by schettino72** [comment]
I added a wiki page: https://github.com/pydoit/doit/wiki/powered-by-doit
