### ISSUE TITLE
Improve error message for command/task/target not found

### ISSUE THREAD

**Issue by schettino72** [pydoit/doit#71]
See https://github.com/pydoit/doit/issues/60#issuecomment-118548453

- [x] level 0: mention`doit help` to see list of tasks
- [x] level 1: only mention `doit help` if `run` (or `build` in nikola) was not specified
- [ ] level 2: suggest similar command/task names

Implementation of level 0 is good enough...

**Comment by felixfontein** [comment]
I started implementing what I had in mind when I wrote that comment: https://github.com/pydoit/doit/compare/master...felixfontein:adjustable-error-messages?expand=1

**Comment by felixfontein** [comment]
Regarding level 3: I think what you mean is already implemented in Nikola (see around https://github.com/getnikola/nikola/blob/master/nikola/__main__.py#L327); see https://github.com/getnikola/nikola/commit/bbfeacb7d527056b3fbbd3ec97d7821c0d8ac9ca and https://github.com/getnikola/nikola/commit/2466123d33faa37dbcea2961728f99b090392586 for the relevant commits and https://github.com/getnikola/nikola/issues/1807 for the discussion.

**Comment by schettino72** [comment]
I didnt bother to implement item 3. closing this anyway.

It should work on nikola out of the box (but didnt test it)

**Comment by felixfontein** [comment]
Cool! Just tested it with Nikola, works fine.
```
$ nikola build test
ERROR: command `build` invalid parameter: "test". Must be a task, or a target.
Type "nikola list" to see available tasks
```
