### ISSUE TITLE
Utilize python-logging for all messages

### ISSUE THREAD

**Issue by ankostis** [pydoit/doit#78]
Would it be an acceptable modification to utilize python's loggin standard library for all messages?

That would facilitate integration of *doit* in larger projects, besides making possible various configurations for the output messages (i.e. adding timestamps, host, etc).

**Comment by schettino72** [comment]
Are you talking about the output produced by `doit` itself or the output coming from a task?

`doit` own output already can be modified/extend through [reporters] (http://pydoit.org/cmd_run.html#custom-reporter). `doit` already provides a few reporters, adding another one that uses logging would be welcome :)

**Comment by ankostis** [comment]
Both.

**Comment by schettino72** [comment]
Although this is an older issue, i am gonna close it as duplicate of #128 because that issue contains an implementation.
