### ISSUE TITLE
Automatic tab-completion inspired from autojump

### ISSUE THREAD

**Issue by StreakyCobra** [pydoit/doit#81]
Hi,

I just discovered this project. It looks very interesting, congrats. Going through the documentation, I found the [tab-completion](http://pydoit.org/cmd_other.html#tabcompletion) functionality kind of complicated.

I remember the [`autojump`](https://github.com/wting/autojump) project doing something very interesting:

There is a [`--complete`](https://github.com/wting/autojump/blob/master/bin/autojump#L115) command line flag that do nothing except printing the completion for the other given arguments. Then, there is a generic [bash](https://github.com/wting/autojump/blob/master/bin/autojump.bash#L27) | [zsh](https://github.com/wting/autojump/blob/master/bin/_j#L4) completion script – that can be installed with the software – which call the same command with the `--complete` flag for generating the completion. This remove the need of a custom completion function and its associated sourcing!

I'm not involved in `autojump`, so excuse any wrong understanding on how it really works :smile:

----

**An example to illustrate (inspired from `autojump`):**

ZSH completion:
```zsh
#compdef doit
cur=${words[2, -1]}

doit --complete ${=cur[*]} | while read i; do
    compadd -U "$i";
done
```

Then when using `doit`:

```sh
$ doit som
$ doit som[TAB]

# This call the `_doit` zsh completion

# The zsh completion above will internally call this (on line 4):
# `doit --complete som`

# The doit program run with these argument will look for
# targets/tasks/whatever beginning with `som` and print them to stdout

# The zsh completion will use what is printed to generate the list of
# possible completion, and eventually complete the line.

$ doit something
```

Advantages:

- No need for custom completion functions: it can be installed with the program.
- Completion can be even smarter. You can return completion that depends on the context (e.g. up-to-date targets no showing, etc.). Python limits are the only limits :v:
- It's easy to extend completion to others shells: completion is no longer shell-dependent (`autojump` as also a completion for [`fish`](https://github.com/wting/autojump/blob/master/bin/autojump.fish#L15) for instance).

I don't know yet if I will be willing/motivated to implement this, but I'm throwing this enhancement idea just in case someone want to go ahead :+1:

Kind Regards,
++ Fab

**Comment by schettino72** [comment]
> This remove the need of a custom completion function and its associated sourcing!

Not really. Your example also includes a ZSH completion file. If you look at `doit` source it includes a "default" completion file that can be used by any project i.e. [zsh](https://github.com/pydoit/doit/blob/master/zsh_completion_doit).

Taking a quick look at autojump, it seems that the "easy" part comes from it installing the completion script when their install script is executed. Putting the completion script in the right location is system dependent. It would be nice if setuptools could handle that, if you know a project that handles it nicely I could add it...

About having the actual implementation in python with `--complete`. Parts of completion system are already written in python. So I am not sure how using this `--complete` technique would make the system better or easier in any way...

If you show me some actual code you might convince me :D

**Comment by StreakyCobra** [comment]
> Not really. Your example also includes a ZSH completion file. If you look at doit source it includes a "default" completion file that can be used by any project i.e. zsh.

Oh sorry, I didn't saw it because when I tried tab-completion it was not working. And when I saw the documentation I assumed – wrongly – their was any default. But it's the Archlinux package that doesn't put completion files at the right place. :sweat_smile: 

> Putting the completion script in the right location is system dependent. It would be nice if setuptools could handle that, if you know a project that handles it nicely I could add it...

There is probably no way to automate this, it is really different for each system. This part is usually the packager's job.

> About having the actual implementation in python with --complete. Parts of completion system are already written in python.

I just looked at the completion, it is more or less the same idea as autojump: getting the completion from the program directly.

> So I am not sure how using this --complete technique would make the system better or easier in any way...

What could be added with the `--complete` approach is the context-dependent completion, example shown below.

> If you show me some actual code you might convince me :dancer:

Because completion works great as is, there is no more big advantages at changing it :+1: So closing this issue.

----

Context-dependent completion could make the system better when using [arguments](http://pydoit.org/task_args.html) for instance. Example:

```sh
$ doit [TAB]
# The actual completion works great here, showing the list of tasks

$ doit py_[TAB]
# Still working great, complete the word with the existing task

$ doit py_params [TAB]
# What can go here are tasks, but by the context you now there
# can also be arguments. But arguments are specific to the
# listed task, and the current `list` method can not complete it
# because the context is not given.
```

With the `--complete` approach (but lets use the `list` keyword):

```sh
$ doit py_params [TAB]

# The `--complete` approach will call this:
$ doit list --complete py_params

# And in the python scripts, you can return the exact completion, knowing
# you have the py_params task which can be followed by one of its parameter
# or another task.

$ doit py_params --par[TAB]
$ doit py_params --param2
```

This is just an example to show advantage of passing the current arguments to the script to give a context-sensitive completion. But it's probably a lot of work for a few use-cases :smile:

**Comment by schettino72** [comment]
The `zsh` can complete on command parameters. It would be really cool if someone add it for bash too (I use bash), but it seems not as easy as zsh.

I rarely use parameters on tasks, so this never bothered me.

**Comment by StreakyCobra** [comment]
> The zsh can complete on command parameters. It would be really cool if someone add it for bash too (I use bash), but it seems not as easy as zsh.

I was not aware of this difficulty. I just tryied: even the `git`  bash completion doesn't complete parameters.

> I rarely use parameters on tasks, so this never bothered me.

Me neither, it's why I closed it ^^
