### ISSUE TITLE
Add support for PosixPath in file dependencies

### ISSUE THREAD

**Issue by btel** [pydoit/doit#95]
In FAQ a `pathlib` is suggested for handling folders and paths:

> file_dep does NOT support folders. If you want to specify all files from a folder you can use a third party library like pathlib ( pathlib was add on python’s 3.4 stdlib).

But current version of `doit` doesn't support `PosixPath`:

```
Traceback (most recent call last):
  File "/home/bartosz/.pyenv/versions/anaconda3-2.3.0/lib/python3.4/site-packages/doit/runner.py", line 125, in select_task
    node.run_status = self.dep_manager.get_status(task, tasks_dict)
  File "/home/bartosz/.pyenv/versions/anaconda3-2.3.0/lib/python3.4/site-packages/doit/dependency.py", line 600, in get_status
    if not os.path.exists(targ):
  File "/home/bartosz/.pyenv/versions/anaconda3-2.3.0/lib/python3.4/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: argument should be string, bytes or integer, not PosixPath
```

A possible solution is converting to string with `str(path)`, but handling `PosixPath` directly would be far more elegant.

**Comment by schettino72** [comment]
Yes. I plan to add direct support for `pathlib`. Do you want try providing a pull-request?

**Comment by btel** [comment]
I am preparing a tutorial about builiding workflows in python. One example will be based on `doit`. I can try the PR, when I finish (in about 2 weeks), but if you want to do it before please go ahead

**Comment by schettino72** [comment]
> I am preparing a tutorial about builiding workflows in python.

`doit` is the best one right? :grimacing: 

I am cleaning the backlog but have more higher priority stuff...

**Comment by Hinidu** [comment]
:+1: for that feature!

**Comment by schettino72** [comment]
@Hinidu " :+1:" doesnt help. If you want this feature implemented faster provide a patch yourself or place a bounty :grinning:

**Comment by Hinidu** [comment]
@schettino72 honest answer :smiley: Challenge accepted #114 :wink:
