### ISSUE TITLE
Passing arguments to tasks: need to specify at least one of short or long?

### ISSUE THREAD

**Issue by andsor** [pydoit/doit#96]
Hey, thanks for this great tool! I just came across the following issue:
For passing arguments to tasks, the [documentation specifies that "short" and "long" names are optional](http://pydoit.org/task_args.html#arguments). However, in my setup it seems as if omitting both gives an error.

dodo.py:
```python
def task_py_param():
    def show_param(param):
        print(param)
    return {'actions':[(show_param,)],
            'params':[{'name':'param',
                       'default':'default value'}],
            'verbosity':2,
            }
```

Running the task:
```bash
$ doit py_param --param=test
ERROR: Error parsing Task: option --param not recognized (parsing options: ['--param=test'])
$ doit help py_param
py_param  

```

Versions:
```bash
$ python --version
Python 3.4.0
$ pip list
doit (0.28.0)
pip (1.5.4)
pyinotify (0.9.6)
setuptools (2.1)
six (1.9.0)
```

**Comment by schettino72** [comment]
If you don't define `long` or `short` you cant use it on the command line.
`name` is just a name, you cant use `--<name>`, you must explicitly set the `long` to be used in the command line.

**Comment by andsor** [comment]
Well thanks for the clarification! I just feel like the documentation could be a bit more explicit here, as the heading in fact says **Passing Task Arguments from the command line**. At least to me it was not clear before your explicit explanation here, that in order to be able to use the command line, one is obliged to specify one of the optional parameters.
Thanks for your consideration!

**Comment by cnperez** [comment]
I have to agree with @andsor. The documentation says:

    Long parameter form, used for e.g. --parameter value when it differs from its name.
    required:	optional
    type:	str

This implies that it would default to "name" unless you specify something different.

**Comment by schettino72** [comment]
@cnperez ok, you are right. andsor didn't point this sentence in the docs... so I missed it.

Can you please submit a pull-request fixing the docs?

**Comment by schettino72** [comment]
@cnperez actually no need PR. it is so trivial that it will be more work to merge than fix myself. thanks for reporting it.

**Comment by mitchbregs** [comment]
@schettino72 - I am running into a similar situation when passing parameters through a yield statement instead of return.  The [documentation](https://pydoit.org/task_args.html) only gives examples of passing parameters in one-off tasks with return statement, whereas I am running a task with for loop through a bunch of data and using a yield statement in order to capture the task actions, targets, dependencies, etc.  However, I am now trying to add parameters to this task:

```bash
doit -f wp/dodo.py external_report --week 1      
ERROR: Error parsing Task: option --week not recognized (parsing options: ['--week', '1'])
```

This is my yield definition:

```

**Comment by schettino72** [comment]
```
doit -f wp/dodo.py external_report:output.stem --week 1      
```

**Comment by mitchbregs** [comment]
Thanks a bunch @schettino72 - loving your work on `pydoit`! 😄

**Comment by schettino72** [comment]
> Thanks a bunch @schettino72 - loving your work on pydoit! smile

Cool, so give it a :star2: :grimacing:
