### ISSUE TITLE
Are sub-tasks and positional arguments supported when used together?

### ISSUE THREAD

**Issue by alexandre-heaume** [pydoit/doit#99]
Hi!

I'm trying to use sub-tasks and positional arguments together. I'm fairly new to doit, so this might not be a sensible use case. Anyway, this is an example `dodo.py`:

    from doit.action import CmdAction
    
    
    def task_do_stuff():
        def do_stuff(pos):
            cmd = 'echo {x}/do_stuff {arguments}'
            return cmd.format(
                x=x,
                arguments=' '.join(pos or []),
            )
    
        for x in ['foo', 'bar']:
            yield {
                'name': x,
                'actions': [CmdAction(do_stuff)],
                'pos_arg': 'pos',
                'verbosity': 2,
            }

Here are the results:

## `doit do_stuff:foo`

`doit do_stuff:foo 1 2 3` does not work, it runs with `bar` instead of `foo`:

### actual

    .  do_stuff:foo
    bar/do_stuff 1 2 3

### expected

    .  do_stuff:foo
    foo/do_stuff 1 2 3

## `doit do_stuff:bar`

`doit do_stuff:bar 1 2 3` works:

    .  do_stuff:bar
    bar/do_stuff 1 2 3

## `doit do_stuff`

`doit do_stuff 1 2 3` does not work, it considers `1`, `2` and `3` to be task names.

### actual

    ERROR: Invalid parameter: "1". Must be a command, task, or a target.

### expected

    .  do_stuff:foo
    foo/do_stuff 1 2 3
    .  do_stuff:bar
    bar/do_stuff 1 2 3

## `doit`

`doit` does not work:

### actual

    .  do_stuff:foo
    ########################################
    TaskError - taskid:do_stuff:foo
    CmdAction Error creating command string
    Traceback (most recent call last):
      File "action.py", line 193, in execute
        action = self.expand_action()
      File "action.py", line 258, in expand_action
        subs_dict[self.task.pos_arg] = ' '.join(self.task.pos_arg_val)
    TypeError: can only join an iterable

### expected

    .  do_stuff:foo
    foo/do_stuff 1 2 3
    .  do_stuff:bar
    bar/do_stuff 1 2 3

Is this the correct behaviour? Is there another way to have subtasks and pass them positional arguments? How can I help you with this?

**Comment by schettino72** [comment]
> `doit do_stuff 1 2 3` does not work

This is not supported. I think that's stretching positional arguments too far.
Can you explain your "real world" use-case ?

This would not be trivial to implement because internally the task `do_stuff` is a task with no actions and a dependency to all sub-tasks. So it is actually executed after the sub-tasks. 
But maybe there is an easier way.

There is a way to pass values from command line to all tasks: `doit.get_var`, have you seen that?

Anyway I guess at least the error message should be improved when you just execute `doit` ...

**Comment by alexandre-heaume** [comment]
It's fine if this isn't supported, you may close the issue then, unless you want to keep it open for the error message fix.

I'll look into `get_var` and see where it takes me, thanks.

The "real world" use case is running command line programs that accept the same arguments and compare the outputs.

**Comment by schettino72** [comment]
something like this?

```
def task_cmds():
    for cmd in ['echo', 'echo 2']:
        yield {
            'name': cmd,
            'actions': ['{} %(pos)s'.format(cmd)],
            'getargs': {'pos': ('compare', 'pos')},
            'verbosity': 2,
            'uptodate': [False],
        }

def task_compare():
    return {
        'actions': [lambda pos: {'pos': ' '.join(pos)}],
        'pos_arg': 'pos',
    }
```

This works must you must specify both tasks in the command line:
`doit cmds compare a b`
